### ISSUE TITLE
绑卡时st更新属性失败文本优化建议

### ISSUE THREAD

**Issue by qingccha-tea** [sealdice/sealdice-core#101]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在A群绑卡但在其他使用同一卡的群试图更新属性得到的错误回执容易使人误解为是在本群绑卡所以属性更新失败，一通解绑操作后陷入迷茫

### 有什么好的想法？

建议对文本作出区分，在本群绑卡所以更新属性失败 和 在其他群绑卡所以更新属性失败 两种情况使用不同的文案回复。

**Comment by Xiangze-Li** [comment]
@qingccha-tea 请你帮忙明确：如何触发你所说的错误回执？

例如：在A群绑卡、在B群绑卡、在B群st更改属性、此时出现错误回执（这个步骤并不复现你所说的问题，你可以参照这个格式）

**Comment by qingccha-tea** [comment]
按当时的方法已经无法复现，似乎是在绑定功能的更新中已经优化了，目前没有问题。辛苦开发组了！

**Comment by Xiangze-Li** [comment]
也感谢你对海豹的支持！
