### ISSUE TITLE
豹语变量：当前日志开启时间

### ISSUE THREAD

**Issue by YS-CC** [sealdice/sealdice-core#1014]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前分日志计时只能通过插件实现，但插件实现的分日志计时必然会增加一条来自于骰娘的log。

### 有什么好的想法？

希望能增加{$t当前日志开启时间}的timestamp格式豹语变量

**Comment by MX-fox** [comment]
可自行在 `lognew` 和 `logon` 时赋值时间戳以记录，想法中的变量并无意义

**Comment by JustAnotherID** [comment]
记录日志的开启时间对绝大多数的跑团用户来说没有太大意义，同时也可以通过自行修改文案执行豹语的方式记录时间，目前不考虑增加对应变量。
等待补充更多必须由海豹提供该该变量才能实现的场景后再讨论，目前先关闭该 issue。
