### ISSUE TITLE
可以更新怪物之锤查询文件的一些6版数据到7版吗？

### ISSUE THREAD

**Issue by cherrybird7** [sealdice/sealdice-core#1015]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

我在写coc扩展的怪物帮助文档时，发现了7版怪锤没有的7版怪物数据，而在写怪物之锤查询时我是直接保留了6版的数据，我自己怪物之锤查询文档已经更新了，请问能顺带把官方的也更新一下吗？
新的条目
"绿神子嗣": "绿神子嗣（Green God, Children of the）\n之后我看到了一个那些部落信奉的“朋友”，开始卸去为了穿过人群的面部伪装。他们巨大的眼睛从昏暗中突出，他们野兽般的牙齿在畸形的嘴里闪闪发光。——拉姆塞·坎贝尔《沃伦唐之下的恐怖》\n绿神子嗣是一种经历过大量变异的退化人种。他们周身被粗糙的毛发覆盖、耳朵细长、长着类似啮齿动物的牙齿、并蹦来蹦去地行进且似乎总在躲避阳光。一般而言，他们生活在复杂的而混乱地底。他们是瓦伦尼部落的末裔，一群崇拜绿神的不列颠人。只要避开他们的巢穴并放任他们行动，他们不过是些无害的可怜人。\n这些生物迅捷而机敏，甚至能用计谋战胜野兽和人类。如果与落单的绿神子嗣发生冲突，他们一定会逃跑。这些家伙在集群时可能发起攻击。这些生物很少远离自己的家园，并且通常成群结队行动。这个部族的成员可以伪装成人类，把他们受诅咒的腐化农产品卖到附近的定居点。他们的目的并非是贸易本身，而是同化人类。\n使用【.help 绿神子嗣属性表】来查看有关绿神子嗣的数值。",
"绿神子嗣属性表": "绿神子嗣，堕落的变异体\n属性 平均值 骰点 \nSTR 65-70 （3D6+3）×5\nCON 80-85 （3D6+6）×5\nSIZ 65 （2D6+6）×5\nDEX 95 （2D6+12）×5\nINT 65 （2D6+6）×5\nPOW 65 （2D6+6）×5\n移动：9\n生命值：14-15\n平均伤害加值：+1D4\n平均体格：1\n平均魔法值：13\n战斗方式\n每轮攻击次数：1（抓或咬）\n格斗 40%（20/8），伤害:爪击1D4+DB;撕咬1D3+DB\n闪避 45%（22/9）\n技能\n聆听 50%, 侦查 50%, 潜行60%。\n护甲：无。\n法术：高于80意志的绿神子嗣知晓联络绿神（纱布-尼古拉斯）和1d6个其他法术。\n理智损失：目击绿神子嗣时损失0/1D4理智值。",

**Comment by fy0** [comment]
我记得已经更新了，可以在内置中翻看一下：
https://github.com/sealdice/sealdice-builtins

**Comment by Xiangze-Li** [comment]
@cherrybird7 我们不掌握怪物之锤的具体文本。如果你手里有最新文本，敬请直接在 https://github.com/sealdice/sealdice-builtins 仓库贡献代码。
