### ISSUE TITLE
[150 Bug] 引用计算属性的骰点结果中间过程丢失

### ISSUE THREAD

**Issue by bigmiin** [sealdice/sealdice-core#1018]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

以下是我在使用150测试版中使用.st &<属性>=<式子>该指令时发现作出了修改，仅列出最终结果而不展示内部单个骰的结果
![3DE388C2DFAB9F7DC0F437DF96DB9D65](https://github.com/user-attachments/assets/cbe16c6b-641e-449e-97e3-0f2ffa309990)
![B947597A5A74B18DEC9F2AE298830A53](https://github.com/user-attachments/assets/234ae1fb-685d-4bb6-aa96-304cb5a22a38)
该骰为豹版本为150测试版+一部分自编译，但理论未动过算法这一部分

### 有什么好的想法？

能否列出单个值的结果，例如图下146正式版骰
![6FEF4AED6F3AA047B4134C43D1C23561](https://github.com/user-attachments/assets/f8330315-2cd7-48c0-bd17-4ebebda2d687)

**Comment by fy0** [comment]
竟有此事，研究一番。。。

**Comment by fy0** [comment]
已经修改，等待汇入主线。显示起来比之前略有一些不同：
>>> &x=d10+d4
>>> x
6[x=5[d10]+1[d4]=6]

**Comment by fy0** [comment]
@bigmiin 修改和编译了新的版本，可以再试试，如果有遇到bug请速速反馈

**Comment by bigmiin** [comment]
![41474d08-590e-4132-a621-d96d0f30f077](https://github.com/user-attachments/assets/51963f3c-5dd6-47eb-a5a0-ee102169c7d1)
大概是没有bug了，非常感谢！！！
