### ISSUE TITLE
[Bug]: 自定义回复的 `公共条件` 无法显示

### ISSUE THREAD

**Issue by MX-fox** [sealdice/sealdice-core#1019]
1.5.0 版本 `公共条件` 无法显示
![image](https://github.com/user-attachments/assets/e705152a-2fed-49ca-a05a-034b05153763)
![image](https://github.com/user-attachments/assets/b63814ff-ae7e-473d-99e7-339fdfb795c1)

**Comment by Xiangze-Li** [comment]
理论上 UI 并没有区分版本，帮忙在 1.4.6 版本也尝试复现一下 @MX-fox

**Comment by MX-fox** [comment]
> 理论上 UI 并没有区分版本，帮忙在 1.4.6 版本也尝试复现一下 @MX-fox

1.4.6 无法复现，只有 1.5.0 会，我的版本是 1.5.0-dev+20240820.5026a91

**Comment by JustAnotherID** [comment]
前端问题，合并后修复。
