### ISSUE TITLE
染色器角色判定问题

### ISSUE THREAD

**Issue by qingccha-tea** [sealdice/sealdice-core#102]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

直接复制的QQ记录放进染色器，同一账号在0点前后会被识别成不同的角色
![A}K6YKB@$DYMX0V}$YLMSQ3](https://user-images.githubusercontent.com/111262215/236675623-f76cfef2-424b-41c5-869a-f3b3dc9001e8.png)
![NLG7~JUH%Q4Y9( )L 6Q)4P](https://user-images.githubusercontent.com/111262215/236675626-3281e49b-ed18-41d8-bda2-80d81fb62930.png)

### 有什么好的想法？

应该是把日期识别成id的一部分了，不知道能不能改）

**Comment by fy0** [comment]
需要一点原文，qq聊天记录里是咋样的

**Comment by qingccha-tea** [comment]
清梦无茶 2023/5/5 23:59:31
（）

焱淼 2023/5/5 23:59:40
李华看了看李老师，有些不忍心地别过头去：“老师你要不还是先走吧，别管我了，从来也没有人管过我，我不值得您这样。”

焱淼 2023/5/5 23:59:58
（我都快哭了，可惜李华不会）

ABCD 0:00:04
（泪目）

**Comment by qingccha-tea** [comment]
第一个括号里面有QQ自带的香烟表情，直接复制出来不显示。
![1](https://github.com/sealdice/sealdice-core/assets/111262215/448d4b37-18d6-4851-80be-7a5612af6190)

**Comment by Xiangze-Li** [comment]
从表现来看，是在识别用户名和时间时只适应了 `用户名 15:04:05` 这种写法，没有考虑到中间可能还有一个日期

**Comment by Fripine** [comment]
> 从表现来看，是在识别用户名和时间时只适应了 `用户名 15:04:05` 这种写法，没有考虑到中间可能还有一个日期

看了一下正则，应该是昵称后面缺少了Q号导致的，如果手动补全Q号则识别无误
![image](https://github.com/sealdice/sealdice-core/assets/84258717/e0c1e416-25e7-446f-8a63-a28b6b4068d5)

> 清梦无茶 2023/5/5 23:59:31
> （）
> 
> 焱淼 2023/5/5 23:59:40
> 李华看了看李老师，有些不忍心地别过头去：“老师你要不还是先走吧，别管我了，从来也没有人管过我，我不值得您这样。”
> 
> 焱淼 2023/5/5 23:59:58
> （我都快哭了，可惜李华不会）
> 
> ABCD 0:00:04
> （泪目）

这段聊天记录是Q聊天窗口里通过文本模式直接复制出来的吗？我个人这边使用文本模式，虽然也会出现部分记录日期消失的情况，但是Q号依旧跟随在昵称后面，直接复制进染色器正常染色

**Comment by qingccha-tea** [comment]
不是tim，当前版本9.7.22（29298）

**Comment by Fripine** [comment]
> 不是tim，当前版本9.7.22（29298）

你使用的是老版本QQ，按照这个步骤开启文本模式后，再复制聊天记录至染色器，看看是否染色有误。
步骤：打开聊天窗口-更多（图标是三个点）-字体选择-文本模式
![image](https://github.com/sealdice/sealdice-core/assets/84258717/123d7224-4bbe-49e5-9d0b-f9ecdeb2aa71)

**Comment by qingccha-tea** [comment]
调整为文本模式后测试识别正常，应该是气泡模式才会识别错误，整明白了，非常感谢开发组（鞠躬
