### ISSUE TITLE
[Bug]: qq群内改群名片海豹不会同步改群名字

### ISSUE THREAD

**Issue by FairyOwO** [sealdice/sealdice-core#1025]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

主动修改群名片之后, 海豹后台不会同步修改群名片, 仍然是原来的名字
<details><summary>图片细节</summary>
<p>

![5042dcff13a0d400901f45a94564d3c0](https://github.com/user-attachments/assets/24573db2-9e84-4967-a884-42ddeee8348e)

<img width="264" alt="{21619884-5439-43e5-9014-39EE65212A40}" src="https://github.com/user-attachments/assets/7929fbe4-ff43-4fcc-9c82-16dc15e73a02">

![image](https://github.com/user-attachments/assets/e32253e8-9814-4577-ba46-5c9bec3bee35)

</p>
</details> 

其中 改名时间在当前提交issue时间的前一天, 改名时间与当前提交issue时间同一天

骰子没有拿到管理员

Lagrange

重新连接lagrange之后正确获取群名字

### 如何复现

同上

### 你期望发生的

正确的获取群名片

### 实际上发生的

没有同步修改群名片

### 日志文件

-

### 海豹核心版本

1.4.6

### 操作系统

linus

### 帐号类型

qq

### 使用协议

-

### 附加内容

-

**Comment by Xiangze-Li** [comment]
设计如此。海豹里的名字是所谓的「角色名」，IM 平台的名字只在角色名不存在时进行初始化用。

提案会导致这样的后果：录入了一个和当前 IM 名一致的角色名，然后修改 IM 名，这时角色名会在用户不知道的情况下修改。这可能对一些用户是期望的，但是显然是有其他用户不期望的。
