### ISSUE TITLE
[Bug]: 使用安卓端UI扫码登陆时被拒绝，显示pc端“版本过低”

### ISSUE THREAD

**Issue by Iansniper** [sealdice/sealdice-core#1047]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

启动安卓核心之后进入网页版UI登陆帐号，按手册要求，使用TIM v3.5.6.3208 的相册扫码功能对二维码进行扫码登陆并点击了确认功能按钮，然而UI端的登陆界面就卡在二维码那里，退出回到日志发现显示“禁止登陆”，“QQ版本过低”，使用其他方式用手机安卓QQ 9.0.95.19320（显示为最新版本）扫码，得出相同结果

### 如何复现

启动安卓核心之后进入网页版UI登陆帐号
按手册要求，使用TIM的相册扫码功能对二维码进行扫码登陆，点击了确认功能按钮

### 你期望发生的

在网页端UI显示账号已链接并可以正常使用

### 实际上发生的

UI端的登陆界面就卡在二维码那里，退出回到日志发现显示“禁止登陆”，“QQ版本过低”，无法使用机器人

### 日志文件

![Image_1726998633147](https://github.com/user-attachments/assets/0932f920-fc92-44c5-81df-cd9c42fab4e9)

### 海豹核心版本

![IMG_20240922_195126](https://github.com/user-attachments/assets/997c9831-9887-4511-b814-a8156c00d9a1)
安卓APP版本 v0.6.1

### 操作系统

安卓9，小米 mix 2s

### 帐号类型

QQ

### 使用协议

账号使用内置客户端设置

**Comment by Xiangze-Li** [comment]
这意味着QQ方面发现了这次登录有问题而禁止你登录。所谓「版本过低」只是一种托辞。

请参：<https://sealdice.github.io/sealdice-manual-next/deploy/platform-qq.html#%E6%9C%89%E5%85%B3-qq-%E5%B9%B3%E5%8F%B0%E6%9C%BA%E5%99%A8%E4%BA%BA%E7%9A%84%E8%AF%B4%E6%98%8E>

**Comment by Fripine** [comment]
自行前去官网下载最新版海豹，然后根据手册对应内容进行登录操作

**Comment by Iansniper** [comment]
> 自行前去官网下载最新版海豹，然后根据手册对应内容进行登录操作

安卓0.6.1就是官网最新版，用TIM扫码相册也是手册里写的，结果都是一样的



> 这意味着QQ方面发现了这次登录有问题而禁止你登录。所谓「版本过低」只是一种托辞。

没办法解决的吗，链接里说这是因为官方很可能封禁了机器人账号，但我在电脑搞这套扫码是正常的，而且我账号也没被封可以正常上QQ，也没被官方发什么警告

**Comment by Fripine** [comment]
> > 自行前去官网下载最新版海豹，然后根据手册对应内容进行登录操作
> 
> 安卓0.6.1就是官网最新版，用TIM扫码相册也是手册里写的，结果都是一样的


**需不需要我再给你贴个直链？**

![image](https://github.com/user-attachments/assets/898a854d-0629-49c5-88c4-b41eff6f82f0)
![image](https://github.com/user-attachments/assets/73c8a645-4b9c-43b6-bf42-fbe0f46be07e)
