### ISSUE TITLE
[150 Bug]: 使用rdn接原因句子该指令后，返回结果中间项缺失

### ISSUE THREAD

**Issue by bigmiin** [sealdice/sealdice-core#1056]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

![rd数字 测试](https://github.com/user-attachments/assets/fb82ddf8-2eda-46cb-aa16-603d5b194e62)
如图，在使用rdn+原因该指令时，中间数字多出一空格，而使用rd+原因该指令时中间数字后跟着骰面数字，怀疑rdn+原因该指令中间结果应该也有一个骰面表现
该豹版本为150自编译，但理论未动算法这一部分
以下为github最新版150dev，同样存在这个问题（纯新无污染刚解压的新dev豹）
![rd150](https://github.com/user-attachments/assets/64099991-a6bb-416b-8eee-7a111f11c518)

### 如何复现

前提：150dev版豹
1.发送.rdn+原因
n为任意数字，但不为空
2.骰子返回带有空格中间值的结果

### 你期望发生的

使用rdn+原因该指令后返回结果为dn=x[Dn]=x
其中n为骰面，x为0-n范围内随机整数

### 实际上发生的

使用rdn+原因该指令后返回结果dn=x =x
x后多出莫名空格
其中n为骰面，x为0-n范围内随机整数

### 日志文件

![rd日志](https://github.com/user-attachments/assets/b9bda03b-d9d4-467d-8970-f4fcd58a6d66)

### 海豹核心版本

150dev

### 操作系统

win10

### 帐号类型

QQ KOOK DODO TG DISCORD

**Comment by fy0** [comment]
收到力，下次改动的时候顺便TrimSpace一下
