### ISSUE TITLE
当KOOK运行骰子时会显示正在玩SEALDICE，能否加个开关或者配置文件以关闭或自定吗

### ISSUE THREAD

**Issue by FacialLIM** [sealdice/sealdice-core#1059]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

KOOK机器人显示正在玩SEALDICE，想更改但是找不到与之相关的配置文件和开关。

### 有什么好的想法？

如果可以的话，可以增加一个自定义或者关闭的选项吗，或者在文件内部有一个可配置的config文件。

**Comment by MX-fox** [comment]
@Szzrain szz佬看看？

**Comment by FacialLIM** [comment]
好的，谢谢
________________________________
发件人: Szzrain ***@***.***>
发送时间: 2024年10月10日 23:45
收件人: sealdice/sealdice-core ***@***.***>
抄送: FacialLIM ***@***.***>; Author ***@***.***>
主题: Re: [sealdice/sealdice-core] 当KOOK运行骰子时会显示正在玩SEALDICE，能否加个开关或者配置文件以关闭或自定吗 (Issue #1059)


不打算实现，可以自行删除 https://github.com/sealdice/sealdice-core/blob/c982148d9d01a268099d9d9fc939e5887981e52f/dice/platform_adapter_kook.go#L352

―
