### ISSUE TITLE
[Bug]: [150 Bug]在webui中修改自动退群阈值和退群批次间隔（分）无法保存。在webui中修改指令前缀重启后会回归默认状态。

### ISSUE THREAD

**Issue by baiyu-yu** [sealdice/sealdice-core#1099]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

在webui中修改自动退群阈值和退群批次间隔（分）无法保存。在webui中修改指令前缀重启后会回归默认状态。

### 如何复现

在webui中修改自动退群阈值和退群批次间隔（分）并点击保存设置。
在webui中修改指令前缀并重启。

### 你期望发生的

可正常保存。

### 实际上发生的

无法保存。

### 日志文件

![image](https://github.com/user-attachments/assets/f8779691-68e4-43d0-874e-5ceba4a14bdb)
![8f4f7a9839c8e87cc21fd9289be91728](https://github.com/user-attachments/assets/8394ce90-322c-4121-8398-60078b7459b6)

### 海豹核心版本

1.5.0-dev

### 操作系统

linux Ubuntu 22.04.4 LTS

### 帐号类型

QQ内置客户端

**Comment by PaienNate** [comment]
@JustAnotherID ID佬看看？这个和配置修改的PR有关么？
