### ISSUE TITLE
[Refactor] 使用标准库的 `math/rand/v2` 替换 `golang.org/x/exp/rand`

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-core#1101]
后者已经于 go1.22 以 `math/rand/v2` 的名义进入标准库

**Comment by Szzrain** [comment]
这是一个供应链问题， [sealdice/dicescript](https://github.com/sealdice/dicescript) 中大量使用了 `golang.org/x/exp/rand` 库，需要先修改上游

**Comment by kenichiLyon** [comment]
@fy0 ds是否考虑相关refactor

**Comment by fy0** [comment]
> @fy0 ds是否考虑相关refactor

暂时不考虑，因为dicescript的编译目标包括了gopherjs，但是gopherjs目前只支持到1.18 / 1.19
