### ISSUE TITLE
[Bug]: kook出现连接报错后，重登导致海豹闪退

### ISSUE THREAD

**Issue by bigmiin** [sealdice/sealdice-core#1108]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

![09212C908CB283384D01EA73578412B2](https://github.com/user-attachments/assets/cfb13196-8631-4ce6-9d2b-b9a1d7098a6d)
如图，海豹出现kook发送消息错误后（如果需要这个日志那我再抓），点击重登出现上图日志，连接失败，再次点击报错海豹闪退

### 如何复现

1、账号设置添加kook，等待日志连接成功
2点击重新登录

### 你期望发生的

kook连接稳定，点击重登后正常连接

### 实际上发生的

kook消息发送错误，点击重登出现报错，再次点击重登海豹闪退

### 日志文件

[panic.log](https://github.com/user-attachments/files/17607485/panic.log)

### 海豹核心版本

![image](https://github.com/user-attachments/assets/590f5d9e-e24d-4d6f-8b31-79e09d1c7632)
原生1030dev豹

### 操作系统

win10

### 帐号类型

onebot正向，内置客户端，kook,dodo,discord,tg,sealchat

**Comment by Szzrain** [comment]
需要闪退时的错误日志（panic.log）

**Comment by bigmiin** [comment]
> 需要闪退时的错误日志（panic.log）

啊，在日志文件那一栏我上传了文件
