### ISSUE TITLE
panic.log 文件权限为 0640 导致以 root 运行时一般用户无法读取

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-core#1117]

**Comment by PaienNate** [comment]
当前设置来源于rclone的权限配置。

依我的印象，0640权限是：
所属用户可读写
用户所属的组可以读
其他用户不可操作。

以root运行时，一般用户无法读取，应当符合0640的权限设置。

想问一下什么场景下需要root运行的日志让一般用户可读取，以及是否有更推荐的设置？

**Comment by Xiangze-Li** [comment]
0644就行了

这个场景可见于以root权限配置为系统服务或者docker运行
