### ISSUE TITLE
[Req] 显式规定部分数据库字段的长度

### ISSUE THREAD

**Issue by PaienNate** [sealdice/sealdice-core#1155]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

注意到部分数据库字段长度较长，触发了MySQL的索引问题：[ERR] 1071 - Specified key was too long; max key length is 767 bytes。

特此提出一个建议，利用当前~~肥美大~~公骰的数据库备份，执行类似SQL:

```sql
SELECT 
MAX(LENGTH(id)),
MAX(LENGTH(log_id)),
MAX(LENGTH(group_id)),
MAX(LENGTH(nickname)),
MAX(LENGTH(im_userid)),
MAX(LENGTH(time)),
MAX(LENGTH(message)),
MAX(LENGTH(is_dice)),
MAX(LENGTH(command_id)),
MAX(LENGTH(command_info)),
MAX(LENGTH(raw_msg_id)),
MAX(LENGTH(user_uniform_id)),
MAX(LENGTH(removed)),
MAX(LENGTH(parent_id))
FROM log_items;
```
从而得到如下所示的长度信息，进而我们可以根据长度信息，正确选择合理的大小。同时建立更合适的索引（依稀记得索引在非常长的字段上，会影响性能）：

7	4	57	104	75	10	5675	1	5	1002	117	91		

### 有什么好的想法？

-

### 其他内容

-

**Comment by bigmiin** [comment]
噢，限制这个的话怪影响用户的，比如lognew文字+图，日志读到的是一段cq码，如果被限制了那要每次都向来找的用户解释会有点麻烦，觉得没有必要限制
