### ISSUE TITLE
[Bug]: windows平台禁止登陆

### ISSUE THREAD

**Issue by Pumaxt** [sealdice/sealdice-core#1168]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

登录的骰无法将生成的回复发送至群组和聊天中
未登录的骰无法登录

### 如何复现

1、于群聊中发送指令
2、下线，试图重新登录
3、禁止登录

### 你期望发生的

可以正常登录，骰可以将对指令的回复发送到聊天中。

### 实际上发生的

在日志中显示回应已生成，而群聊中并没收到骰的回复。
试图重新登陆的时候，报错[FATAL]: Tag禁止登录
骰的账号状态正常未收到平台警告。

### 日志文件

<img width="587" alt="Screenshot 2024-12-28 153037" src="https://github.com/user-attachments/assets/07dcb995-3355-44dd-994f-9e15f8b3b8c9" />

### 截图

![3dcea2f2052c69da098984f3d95e66e2](https://github.com/user-attachments/assets/81ea14c4-ab9e-4bb6-9901-75dc4a427dd2)
![33VZN(C )VQN9(6C%R{WTC9](https://github.com/user-attachments/assets/4a57e37d-82e8-45ab-91eb-9d16c7f209eb)

### 海豹核心版本

1.4.6

### 操作系统

windows x64

### 帐号类型

QQ

### 使用协议

Lagrange

### 附加内容

昨日（2024/12/27）使用正常
已按照https://github.com/LagrangeDev/Lagrange.Core/issues/715所提供的解决方案更新了30366 签名，依然无法更新

**Comment by kenichiLyon** [comment]
内置客户端换为分离部署
详见海豹用户群公告
![Screenshot_2024-12-28-16-13-45-122_com.tencent.mobileqq.jpg](https://github.com/user-attachments/assets/3594f9e2-1bae-4ac3-83c7-a44d8061cb55)

内置客户端更新还需要时间，还请稍等

**Comment by Pumaxt** [comment]
> 内置客户端换为分离部署 详见海豹用户群公告 ![Screenshot_2024-12-28-16-13-45-122_com.tencent.mobileqq.jpg](https://private-user-images.githubusercontent.com/128369797/399063475-3594f9e2-1bae-4ac3-83c7-a44d8061cb55.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNzc1NTUsIm5iZiI6MTczNTM3NzI1NSwicGF0aCI6Ii8xMjgzNjk3OTcvMzk5MDYzNDc1LTM1OTRmOWUyLTFiYWUtNGFjMy04M2M3LWE0NGQ4MDYxY2I1NS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyOFQwOTE0MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDA3MTBmYjNiY2E2MmNhYWY3NDgyYzZhYzVjYzEzMWE4NTAxZWM1NmEyMjFjOGM3NmZjZTM1Y2M3MDM1MGQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sFiR8xjxjHxM6jBABOwZinVSlCvxUBcPW_gqI3yU2EI)
> 
> 内置客户端更新还需要时间，还请稍等

非常感谢！

**Comment by wcwq98** [comment]
哪有群，来个

**Comment by kenichiLyon** [comment]
> 哪有群，来个

diceweizaima.com 看官网

**Comment by Szzrain** [comment]
looks solved
