### ISSUE TITLE
[Bug]: 已经按照日志提示进行更改但依然无法正常登陆

### ISSUE THREAD

**Issue by Dorotaluosiyuan** [sealdice/sealdice-core#123]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

按照日志提示进行了协议更改等操作但依然无法正常登陆海豹

### 如何复现

1、在1.2.3版本触发自定义回复
2、提示账号风控
3、重新登陆刷新风控，但下一秒重新风控
4、将1.2.3更新至1.2.6
5、登陆失败

### 你期望发生的

正常登陆海豹

### 实际上发生的

显示：你的账号涉嫌违规被限制在非常用设备登录, 请在手机QQ登录并根据提示完成认证，但手机上并没有相关指示。尝试更换协议但依然无法正常登陆

### 日志文件

![X`L4Q4 YWLYSQTGFR}4THJC](https://github.com/sealdice/sealdice-core/assets/127924132/6104df09-edd8-45aa-9bcf-21d02f484880)
![QC2WTCF 7_SZ_CZPB`(DDLE](https://github.com/sealdice/sealdice-core/assets/127924132/17522418-befc-45eb-ad6f-ebbbe8b9d744)

### 截图

![X`L4Q4 YWLYSQTGFR}4THJC](https://github.com/sealdice/sealdice-core/assets/127924132/8da0609a-fc1e-4890-87d5-b61b8bc30bab)

### 海豹核心版本

1.2.6 v20230410

### 操作系统

win11

### 帐号类型

QQ

### 使用协议

AndroidPad

**Comment by Szzrain** [comment]
请使用手表协议空密码进行登录，如果依然无法成功请尝试使用其他账号或使用其他平台
