### ISSUE TITLE
[Bug]: 抽牌_找不到牌组_存在类似这一项会将用"_keys"隐藏的牌堆关键词也显示出来

### ISSUE THREAD

**Issue by Director259** [sealdice/sealdice-core#139]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

牌堆内部用"_keys"隐藏的牌堆关键词会在相似联想词中显示

### 如何复现

发送任意.draw 含有隐藏关键词的关键词

### 你期望发生的

联想关键词和.draw keys指令一样不会显示隐藏关键词

### 实际上发生的

隐藏的牌堆关键词被联想关键词显示

### 日志文件

![QQ图片20230726124436](https://github.com/sealdice/sealdice-core/assets/127825341/a43dcf07-28aa-4cec-8fe9-72f800beb0be)
![_(5N)_SSK@F2{{FDI7`1E A](https://github.com/sealdice/sealdice-core/assets/127825341/e4fa76fa-1d81-46b6-9fc4-2a18db0c120b)
![@A@DUT8}) XG@SW{2IEZ7XR](https://github.com/sealdice/sealdice-core/assets/127825341/7741f5c6-c70b-4c22-8138-7907d0700c82)

### 海豹核心版本

SealDice 1.2.6 v20230410

### 操作系统

windows

### 帐号类型

qq，虽然我想其他平台应该一样

### 附加内容

如果可以的话.draw keys没有关键词的话可以显示没有找到这种提示

**Comment by Xiangze-Li** [comment]
`.draw search <>`也会将设定为不导出的牌组名暴露出来
