### ISSUE TITLE
修改变量{$t检定计算过程}的建议

### ISSUE THREAD

**Issue by ChunChong777** [sealdice/sealdice-core#150]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

展示奖惩骰计算过程的变量{$t检定计算过程}在最前面带有逗号。因为这个逗号无法删去，导致修改自定义文案时在美观方面受到限制。
如：，([D100=92，惩罚 3])

### 有什么好的想法？

希望可以去除变量中的逗号，将逗号改入{COC:检定_单项结果文本}的文案中。

**Comment by fy0** [comment]
这种中间计算过程目前是难以修改的，逗号存在的原因是这种：

```
.r 2d(d30)
<氪豹>掷出了 2d(d30)=[2d28=23, 20+3]=23
```

目前暂无更为理想的中间过程方案，如果有建议可以提出。
