### ISSUE TITLE
希望添加[ra难度检定]原始判定值的变量

### ISSUE THREAD

**Issue by ChunChong777** [sealdice/sealdice-core#151]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

现在的ra难度检定只判定成功与否，不判定成功等级，无法满足在难度检定时提示成功等级的需求。
如：大成功，大失败，远距离射击，弹幕射击，带难度的对抗

而现有的变量仅能获取到经过除2除5处理后的{$t判定值}，即使想通过修改自定义文案来处理该需求也行不通。

### 有什么好的想法？

更改指令太过麻烦，并且不能迎合所有人的需求，在此只希望能够添加一个获取初始判定值的新变量，让用户可以通过自定义文案处理更多情况。

**Comment by Xiangze-Li** [comment]
不同成功等级对应不同结果的情况下，直接使用 `ra 技能` 再由人来判定似乎是更加可行的方案? 

例如, 如果希望在 `ra 困难侦查` 的情况下判定是否同时达成了极难成功, 这就需要一个 困难判定线*2/5 的极难判定线. 判定逻辑变成了 

1. 达到判定线的 2/5 → 极难成功
2. 达到判定线 → 成功(因为已经限定了难度, 这里不会判定为困难成功)
3. 没有达到判定线 → 失败

这反而与任何一条规则都不对应, 个人感觉会造成更多理解上的困难.

**Comment by ChunChong777** [comment]
>

**Comment by ChunChong777** [comment]
问题就是出在除法上，判定值是向下取整的。
比如15的技能，困难成功是7，极难成功是3，可是7*2/3向下取整后是2。
只有一个困难判定值7的情况下，是无法判断原判定值是14还是15的。类似的还有4和5，24和25，34和35等。

**Comment by Feather099** [comment]
我理解你的需求了，你希望能在难度检定下面依旧显示难度等级。
*思考
我这里有一个比较不算办法的临时方案，就是{$tSuccessRank}。在例如 .ra 困难侦查 的环境下这个成功等级依然会有变化（应该是大成功4-普通成功1）。
如果你不介意将这一条写得比较复杂的话，在后面附上一段对于{$tSuccessRank}的if语句然后按照情况调用上面的对应语句就可以了（大概吧我我完全是脑测的）。
有什么问题也可以继续指出，我就是提出一个自己的想法。（溜走）

**Comment by fy0** [comment]
隐约记得有变量？前段时间群里讨论过这个问题，好像群里是说“规则书并未提及当要求困难成功时，骰出极难成功会怎样”。
只有大成功是特殊的，因此1.4版本的检定增加了对大成功的额外提示：
```
D100=66/30 失败！还是有点难吧？
D100=1/30 成功了！这要费点力气(大成功)
```

**Comment by ChunChong777** [comment]
已解决，前几天才发现$tSuccessRank这个变量，不过还有个问题要补充。
$tSuccessRank变量的检查存在困难。
在我对自定义文案的测试中发现，所有的判定文案内豹语的执行都早于变量赋值，这导致如果在判定文案中比对$tSuccessRank，实际上比对的是上一次检定的成功登记。
但如果在检定文案或检定_单项结果文本文案中比对$tSuccessRank，则找不到一个变量来提示当前检定的难度等级。
我的解决办法是，自定了一个叫$t难度等级的变量，在所有的判定文案内都都根据调用情况对其进行了赋值，然后在检定——单项结果文本文案中比对¥t难度等级和$tSuccessRank来决定回复。
如图：
![QQ截图20231019021035](https://github.com/sealdice/sealdice-core/assets/124105855/d1d160c9-3dee-4529-9841-88f274b6cd14)


![QQ截图20231019021101](https://github.com/sealdice/sealdice-core/assets/124105855/65e965e6-cede-468a-91a2-07f8af54bf32)
