### ISSUE TITLE
[Bug]: {$t原因}部分的格式为“任意文字%任意文字？”时发生指令执行异常

### ISSUE THREAD

**Issue by Mouwoo** [sealdice/sealdice-core#157]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

使用“.r 任意文字%任意文字？”格式的指令（比如.r 博德之门3价格低于原价%几我再买？）时发生发生指令执行异常。

### 如何复现

在任何平台对骰子使用”.r 任意文字%任意文字？“格式的指令。

### 你期望发生的

返回正常的带有掷骰原因的掷骰结果语句。

### 实际上发生的

返回指令执行异常语句。

### 日志文件

![image](https://github.com/sealdice/sealdice-core/assets/63538532/f3125feb-f5c0-4bea-9cd0-8877917aa0b6)

### 截图

![image](https://github.com/sealdice/sealdice-core/assets/63538532/20a4bd06-137d-41d6-b8b5-16e8133ee6be)
![image](https://github.com/sealdice/sealdice-core/assets/63538532/db009b8f-50fa-4f76-8e0b-4e8185e8d9eb)
![image](https://github.com/sealdice/sealdice-core/assets/63538532/26fc0bc9-6030-45ab-9b80-4df15d73596f)

### 海豹核心版本

1.2.6 v20230410

### 操作系统

Windows Server 2012R2

### 帐号类型

QQ

**Comment by Xiangze-Li** [comment]
原因是这条命令没有显式指明骰点表达式，而原因句中又含有`%`。这导致原因被解析成骰点表达式，句中的`%`被解析成了modulo运算符，`%`之前和之后的字符被分别解析成变量名，进而得到0值，最终造成`除以0`错误。

如果指明了骰点表达式，则后面的原因句可以正常地被识别为原因。


![Image](https://github.com/sealdice/sealdice-core/assets/45380560/b443ace6-2819-4e6d-b451-9c2d7b9fa473)

**Comment by fy0** [comment]
原来是被除数为0没有正确报错，修好力
![image](https://github.com/sealdice/sealdice-core/assets/1579850/c3ab9b7d-749b-4148-8639-76a9508ddd35)
