### ISSUE TITLE
角色卡pc list时添加对应序号或者序列号，可通过对应序号进行删卡绑卡

### ISSUE THREAD

**Issue by Director259** [sealdice/sealdice-core#159]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

有pl奇特录卡操作导致角色卡建成时是名字加一长串技能名的形式，这种卡换绑其他卡之后就没法用对应角色卡名字绑卡回来或者进行删卡操作了（很蠢但是真的有......）

### 有什么好的想法？

角色卡pc list时添加对应序号或者序列号，可通过对应序号进行删卡绑卡

**Comment by fy0** [comment]
#191
