### ISSUE TITLE
类似塔骰的.st cp功能，可以将指定卡数据复制或转移给群内指定账号上

### ISSUE THREAD

**Issue by Director259** [sealdice/sealdice-core#160]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

有大号突然出事只能用小号的，重新录卡时有时候会忘了中间被扣去多少血量或者san值
似乎也可以做成预设卡的形式

### 有什么好的想法？

st cp(copy) 卡名@指定对象，进行指定角色卡当前数据的转移

**Comment by Xiangze-Li** [comment]
这里似乎可以使用代骰 st export 之后手动复制录入来实现，有必要单独做一个指令吗？

@fy0

**Comment by Xiangze-Li** [comment]
请你帮忙明确设想中的使用方式，如果能够以用户和骰子的对话给出应该会比较清晰。 @Director259

**Comment by Director259** [comment]
> 请你帮忙明确设想中的使用方式，如果能够以用户和骰子的对话给出应该会比较清晰。 @Director259

思，这个是我去年提的都有点忘了（你，实现形式的话我这会也没地方找个活的塔骰用
预想的话应该是：
玩家a：.st cp 卡名 @玩家b
骰子：已为玩家b创建<卡名>并录入玩家a<卡名>当前属性

不过已经有st export指令后感觉或许也不太需要了，而且好像也容易跟代骰的st造成混用#思，或许可以考虑直接关掉这个issue

**Comment by Xiangze-Li** [comment]
把「我」的数据复制给别人 和 把其他人的数据复制给「我」都可以通过代骰完成，并且都有一定可能违背对方的意愿。

又考虑到，塔系的角色管理逻辑和海豹有比较大区别，不适宜直接移植。考虑不实现这个功能。
