### ISSUE TITLE
支持全局变量

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-core#170]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

当前的变量机制，只有 临时变量、用户变量、群组变量、角色卡变量 4种，似乎还缺少全局变量的支持

**Comment by fy0** [comment]
全局变量不存在的原因是太容易被滥用，另一方面就是rollvm的功能太弱，更高级的功能考虑在dicescript实装后加入
