### ISSUE TITLE
[Bug](DND): 属性豁免熟练无法录入

### ISSUE THREAD

**Issue by Szzrain** [sealdice/sealdice-core#179]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [x] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

基础属性豁免无法录入熟练项

### 如何复现

![image](https://github.com/sealdice/sealdice-core/assets/54656633/ff0e8010-46f6-405f-bf87-c7c541f199e9)

### 你期望发生的

上图中显示按照PHB规则应当为+7，即+5力量调整值和+2熟练加值

### 实际上发生的

豁免熟练没能录入，实际中只包含了+5的力量调整值

### 日志文件

——

### 海豹核心版本

SealDice 1.2.6 v20230410

### 操作系统

——

### 帐号类型

——

**Comment by fy0** [comment]
等一个dnd模块的重构。。。

**Comment by fy0** [comment]
我认为最新的commit解决了这个问题
