### ISSUE TITLE
设置CQHTTP的位置为非必填项

### ISSUE THREAD

**Issue by PaienNate** [sealdice/sealdice-core#181]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

如题，在服务器上已运行Mirai+Onebot插件，或已有配置好的CQHTTP时，应当无需**必须设置**go-cqhttp的位置，仅输入WS连接位置即可。

### 有什么好的想法？

或许可以将go-cqhttp分离打开时的设置改为选填项？

**Comment by PaienNate** [comment]
我是傻狗多有打扰.jpg

**Comment by fy0** [comment]
已实现，关闭

**Comment by MX-fox** [comment]
当程序目录未填写时不可点击下一步
<img width="392" alt="image" src="https://github.com/sealdice/sealdice-core/assets/106176511/62c08841-5312-41a9-a162-4f50be991969">
<img width="389" alt="image" src="https://github.com/sealdice/sealdice-core/assets/106176511/d6f81b6f-2a34-4d66-a679-f8cd49dcc37e">
