### ISSUE TITLE
新版通知平台做主次划分

### ISSUE THREAD

**Issue by Director259** [sealdice/sealdice-core#190]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

通知发送目前会通知所有平台，导致消息量增多且无法区分来源平台（主要是存活通知上）

### 有什么好的想法？

存活消息跨平台发送有存在的必要，毕竟kook这种在海豹界面无法看出掉线了没，目前的想法是，在ui界面添加一个主平台可以统一发送通知，其他平台只保留该平台本身的通知，主平台那边最好还能标注一下通知消息的来源平台，比如加个前缀-kook:/dicsord:这种，或者看看其他人有没有更好的想法。

**Comment by fy0** [comment]
暂时没有前缀，但是存活消息改为了全平台发送

**Comment by fy0** [comment]
暂时关闭 如果遇到新问题再说
