### ISSUE TITLE
[Bug]: 使用默认骰面数（即.rd）时，若掷骰原因内含有符号，则会错误识别为表达式

### ISSUE THREAD

**Issue by ChangingSelf** [sealdice/sealdice-core#201]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

使用骰子的用户除了跑团用户之外，还有安科用户，安科是一种使用骰子来影响走向的文学形式。

在写安科的时候，通常会使用100面骰子，并根据情况附加一些修正值作为优劣势修正。例如：

```
主角的侦查检定（过50通过，望远镜+20，环境复杂-20）：d100=51，通过
```

（注：在安科中，就算修正值相抵消，一般来说也应当写出来而不是直接省略）

这种情况下，如果完整写出骰面数，则可以正常掷骰，但如果使用省略骰面数的rd来掷骰，则会因为将描述修正值的加号和减号识别为表达式。如图所示：

![image](https://github.com/sealdice/sealdice-core/assets/59358729/6a033d72-8a36-45b6-8651-014385c8e131)

```
<User>
.rd100 主角的侦查检定（过50通过，望远镜+20，环境复杂-20）

海豹核心
<User>主角的侦查检定（过50通过，望远镜+20，环境复杂-20）:d100=30

<User>
.rd 主角的侦查检定（过50通过，望远镜+20，环境复杂-20）

海豹核心
<User>，环境复杂-20）:d主角的侦查检定（过50通过，望远镜+20=0[d主角的侦查检定（过50通过，望远镜=0] + 20=20
```

### 如何复现

在`r`指令中直接使用`d`而非指定骰面数，并在掷骰原因中任意位置添加表达式符号

### 你期望发生的

应当与指定骰面数时表现一致，正确计算，而非将掷骰原因视作掷骰表达式的一部分

### 实际上发生的

将掷骰原因视作了掷骰表达式的一部分

### 日志文件

![image](https://github.com/sealdice/sealdice-core/assets/59358729/6a033d72-8a36-45b6-8651-014385c8e131)

### 海豹核心版本

1.3.0 v20230910

### 操作系统

Windows 10 专业版 22H2

### 帐号类型

仅搭载了QQ，该问题在QQ账号和web UI上都有。

**Comment by Xiangze-Li** [comment]
与#157本质上是类似的

**Comment by fy0** [comment]
空格断句问题。修改rollvm，我很慌张

**Comment by fy0** [comment]
改好力
