### ISSUE TITLE
综合设置中的文案设置移动到自定义文案

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-core#206]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

![image](https://github.com/sealdice/sealdice-core/assets/45380560/7a83b2fa-acc3-46f8-9710-8a9a5e33026c)

`.help 骰主`, `.help 协议` 和 `.bot 附加文本` 三项, 因历史遗留问题在「综合设置」下, 应当移到「自定义文案」下以统一

**Comment by Director259** [comment]
干脆新增一个help自定义板块？

**Comment by Xiangze-Li** [comment]
需要一个全栈dalao来同时改前端和后端（
