### ISSUE TITLE
[Bug]: 删除了的插件基础设置内不会消失

### ISSUE THREAD

**Issue by MX-fox** [sealdice/sealdice-core#207]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

删除了的插件基础设置内不会消失

### 如何复现

1.添加插件
2.删除插件
3.查看基础设置扩展列表

### 你期望发生的

删除了的插件于基础设置扩展列表消失

### 实际上发生的

删除了的插件于基础设置扩展列表没有消失

### 日志文件

<img width="146" alt="image" src="https://github.com/sealdice/sealdice-core/assets/106176511/93948fe5-f228-417d-81c7-4ad9f541bf67">
<img width="210" alt="image" src="https://github.com/sealdice/sealdice-core/assets/106176511/fe710d59-f9db-4f77-8454-4a468da0780c">

### 海豹核心版本

1.3.0

### 操作系统

Windows11

### 帐号类型

QQ

**Comment by Szzrain** [comment]
Duplicated at sealdice/sealdice-ui#10

**Comment by Szzrain** [comment]
在core仓库也挂一个吧，ui那边看的人不多
