### ISSUE TITLE
希望以变量值调用牌堆，让#{DRAW-`{$t1}`}这种写法能够识别

### ISSUE THREAD

**Issue by shivaree0** [sealdice/sealdice-core#216]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前遇到要根据变量的值来确定抽取哪一个牌堆的情况,并且涉及牌堆数量非常可观，只能人力搬砖。在语句中完整列出所有可能变量的值，然后判断，来匹配需要的牌堆。
既不方便也占文本.....如果牌堆数量庞大，这砖甚至可能写不下....

### 有什么好的想法？

所以或许....可以增加对牌堆格式内，牌堆名字部分的变量优先解析？
让豹豹在收到#{DRAW-`{$t1}`}或者类似写法时，能先获取到{$t1}的内容。
/例:如果#{DRAW-`{$t1}`},{$t1=`早上好`}，先获取{$t1}的内容，即:早上好，将其放入原本的牌堆格式中，得到#{DRAW-早上好}，再抽取“早上好”牌堆将结果填入语句。

*捧着碗等路过的菩萨们掉落一些pr

还有一个不知是不是类似的转义问题，牌堆文档内，在套用内套用时如果多次涉及[$t海豹变量]这种需要转义的方括号，可能会格式错误。
/例: {"_测试0": [
    "111",
    "222"
  ],
  "测试": [
    "[$t1={_测试0};$t输出=`[$t1]输出`]"
  ]}

抽取测试牌堆时会格式错误。

**Comment by JustAnotherID** [comment]
第二个问题已有相关支持，可以去[「海豹手册」](https://dice.weizaima.com/manual/#json%E7%89%8C%E5%A0%86%E6%8A%80%E5%B7%A7)查看。
例如示例中的demo写法如下：
```json
{
  "_在哪":["在卧室"],
  "_动作":["睡觉"],
  "_做什么":["{_在哪}{_动作}"],
  "_主语":["我"],
  "事件":["{_主语}{_做什么}"]
}
```
效果如下：
<img width="680" alt="image" src="https://github.com/sealdice/sealdice-core/assets/42864805/b0248385-0094-41e1-af8e-fa2f3a58aefd">

**Comment by shivaree0** [comment]
> 第二个问题已有相关支持，可以去[「海豹手册」](https://dice.weizaima.com/manual/#json%E7%89%8C%E5%A0%86%E6%8A%80%E5%B7%A7)查看。 例如示例中的demo写法如下：
> 
> ```json
> {
>   "_在哪":["在卧室"],
>   "_动作":["睡觉"],
>   "_做什么":["{_在哪}{_动作}"],
>   "_主语":["我"],
>   "事件":["{_主语}{_做什么}"]
> }
> ```
> 
> 效果如下： <img alt="image" width="680" src="https://user-images.githubusercontent.com/42864805/268156510-b0248385-0094-41e1-af8e-fa2f3a58aefd.png">

咦咦咦，那是我套赋值时格式套错了吗…… *迷茫 晚点回去再试试……打扰了！以及大感谢！

**Comment by shivaree0** [comment]
> 第二个问题已有相关支持，可以去[「海豹手册」](https://dice.weizaima.com/manual/#json%E7%89%8C%E5%A0%86%E6%8A%80%E5%B7%A7)查看。 例如示例中的demo写法如下：
> 
> ```json
> {
>   "_在哪":["在卧室"],
>   "_动作":["睡觉"],
>   "_做什么":["{_在哪}{_动作}"],
>   "_主语":["我"],
>   "事件":["{_主语}{_做什么}"]
> }
> ```
> 
> 效果如下： <img alt="image" width="680" src="https://user-images.githubusercontent.com/42864805/268156510-b0248385-0094-41e1-af8e-fa2f3a58aefd.png">

这个例子写草率了，不涉及海豹变量的话原来是没问题的…… 
修改了一下问题描述和例子……（抽象度++（应该没再有问题吧…… (豹头痛哭.jpg)
