### ISSUE TITLE
将UI界面中的指令运行数永久记住，重复添加帐号时继承

### ISSUE THREAD

**Issue by fy0** [sealdice/sealdice-core#225]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

**Comment by fy0** [comment]
先和和看 不过觉得数据库似乎太隆重哩，我还说丢dice.yaml完事

**Comment by Xiangze-Li** [comment]
> 先和和看 不过觉得数据库似乎太隆重哩，我还说丢dice.yaml完事

丢dice.yml也过于随便了（
