### ISSUE TITLE
希望新增当master指令识别@前缀不回复功能

### ISSUE THREAD

**Issue by MX-fox** [sealdice/sealdice-core#227]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

当群内有多个骰娘，@其中一位骰娘使用.master指令，其他骰娘也会触发master指令

### 有什么好的想法？

当master指令识别@前缀时不回复
（ps：当botoff或添加botlist时不会触发，所以此需求优先度不高）

### 其他内容

<img width="574" alt="image" src="https://github.com/sealdice/sealdice-core/assets/106176511/69081e84-64f8-49a5-899d-8836d51d1c9b">

**Comment by fy0** [comment]
狐狸点头.gif

**Comment by fy0** [comment]
完成力！
