### ISSUE TITLE
希望自定义回复可以自定义cd

### ISSUE THREAD

**Issue by MX-fox** [sealdice/sealdice-core#228]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

骰娘的自定义回复会被用户当作娱乐功能反复触发

### 有什么好的想法？

希望自定义回复可以自定义cd：
1.可以自定义本群共享自定义回复cd
2.可以自定义单人自定义回复cd
（ps：虽然可以通过赋值和判断变量实现cd功能，但是当自定义回复数量过多时操作繁杂，本需求优先级不高）

**Comment by MX-fox** [comment]
海豹已有的自定义回复的响应间隔为单条自定义回复，希望新增的是所有自定义回复的共享cd

**Comment by oissevalt** [comment]
Closed because of https://github.com/sealdice/sealdice-core/pull/467
