### ISSUE TITLE
支持过长文本转链接

### ISSUE THREAD

**Issue by Director259** [sealdice/sealdice-core#234]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

过长的文本会导致无法发出，比如过长的黑名单列表或者查询文本

### 有什么好的想法？

支持这一部分以链接形式转出，或者提供用户可以自行转链接的接口

**Comment by Szzrain** [comment]
我觉得更好的解决方式是自动分段，依赖一个第三方api感觉并不可靠

**Comment by Xiangze-Li** [comment]
确认现在已经有自动分段逻辑, 但是分段的阈值 (5000 个字节) 或许太高了. 可以考虑优化一下现有逻辑

`dice/platform_adapter_gocq_actions.go:577` 的 `func textSplit(input string) []string`

**Comment by Xiangze-Li** [comment]
修改了QQ平台切分长文本的逻辑, 现在 2000 字节 (约 667 汉字) 就会进行切分.

**Comment by fy0** [comment]
之前的5000字节是QQ平台的上限，当时长短文本风控完全属于玄学，现在长文本很容易被控吗？

**Comment by Director259** [comment]
> 之前的5000字节是QQ平台的上限，当时长短文本风控完全属于玄学，现在长文本很容易被控吗？

不确定，看号，不过确实见过长文本会被吞但是分割后的短文本能发出来的骰子，还有过高版本的签名似乎也有长文本或多段文字签不过来导致当场闪退暴毙的情况（不过见过的不多
