### ISSUE TITLE
提供清理上古备份的按钮

### ISSUE THREAD

**Issue by fy0** [sealdice/sealdice-core#239]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

自动备份可能太多了

**Comment by Xiangze-Li** [comment]
需要细化

1. 需不需要保留一部分备份？
2. 如果需要，保留的标准是直接写死，还是要支持用户随意修改？
3. 是否要区别对待自动备份和手动备份？
