### ISSUE TITLE
将gocq进程分离为守护进程，例如设计为海豹关闭后5分钟再退出，如果中途重启海豹，则继续使用之前的gocq

### ISSUE THREAD

**Issue by fy0** [sealdice/sealdice-core#259]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

重启海豹的话，gocq会中断

### 有什么好的想法？

无痛更新

**Comment by JustAnotherID** [comment]
在gocq停更的今天，这个issue还有必要么，是不是该关了（悲

**Comment by fy0** [comment]
> 在gocq停更的今天，这个issue还有必要么，是不是该关了（悲

好象是的，关了吧 新时代来力
