### ISSUE TITLE
添加 WebUI 自订项目，使骰子不响应群组中裸 `.bot` 指令

### ISSUE THREAD

**Issue by Verplitic** [sealdice/sealdice-core#266]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

**Comment by MX-fox** [comment]
私聊骰娘不可以@，导致无法私聊bot

**Comment by MX-fox** [comment]
> 私聊骰娘不可以@，导致无法私聊bot

<img width="311" alt="image" src="https://github.com/sealdice/sealdice-core/assets/106176511/77efab0f-70b1-4595-a42f-26a6b43443a8">
同时导致裸退群指令也无法触发

**Comment by Verplitic** [comment]
群聊不响应裸退群是故意设计，我本地测试能够响应私聊bot
