### ISSUE TITLE
ui界面帮助文档上传增加添加新分组的选项

### ISSUE THREAD

**Issue by Director259** [sealdice/sealdice-core#280]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在ui界面不能直接新增分组，只能传到已有分组中，需要自己去手动处理骰子文件夹再重载导入

### 有什么好的想法？

增加一个新增分组功能，进一步自动化（你

**Comment by JustAnotherID** [comment]
输入框是可以输入新分组的，这个功能已经有了（

**Comment by Xiangze-Li** [comment]
> 输入框是可以输入新分组的，这个功能已经有了（

输入框能否直接输入似乎是平台/浏览器相关的。Windows版Edge浏览器支持直接输入不存在的名字，但iPad版的Edge浏览器就不支持直接输入，而只能从「默认」「COC」「DND」中选择。

**Comment by Director259** [comment]
> > 输入框是可以输入新分组的，这个功能已经有了（
> 
> 输入框能否直接输入似乎是平台/浏览器相关的。Windows版Edge浏览器支持直接输入不存在的名字，但iPad版的Edge浏览器就不支持直接输入，而只能从「默认」「COC」「DND」中选择。

去测试了一下，电脑端应该没啥问题我自己是默认chrome，手机端默认浏览器，百度浏览器也可以呼出输入键盘，其他浏览器手机端没有暂时还没测，ipad默认浏览器safari呼出键盘失败（ipad你好菜

**Comment by JustAnotherID** [comment]
> > > 输入框是可以输入新分组的，这个功能已经有了（
> > 
> > 
> > 输入框能否直接输入似乎是平台/浏览器相关的。Windows版Edge浏览器支持直接输入不存在的名字，但iPad版的Edge浏览器就不支持直接输入，而只能从「默认」「COC」「DND」中选择。
> 
> 去测试了一下，电脑端应该没啥问题我自己是默认chrome，手机端默认浏览器，百度浏览器也可以呼出输入键盘，其他浏览器手机端没有暂时还没测，ipad默认浏览器safari呼出键盘失败（ipad你好菜

那是element plus或者ipad的bug？阿巴阿巴
