### ISSUE TITLE
扩展支持别名

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-core#302]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在操作coc7和dnd5e这两个扩展时，有时会记不住准确的名字。

如果能把coc别名到coc7，dnd和dnd5别名到dnd5e，或许可以更方便。

总的来说，是要支持一个扩展在注册自己的名字同时注册若干个别名。这些别名应当要求互不冲突、可以和本名等效使用。

**Comment by Xiangze-Li** [comment]
> 如果能把coc别名到coc7，dnd和dnd5别名到dnd5e，或许可以更方便。

写死不可行, 需要实现为支持编辑

**Comment by Szzrain** [comment]
应该已经完成了？先行close掉
