### ISSUE TITLE
[Bug]: gocqhttp的“faststart”启动参数未生效

### ISSUE THREAD

**Issue by Krimiston** [sealdice/sealdice-core#303]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

海豹骰启动gocq时，faststart参数没有生效。

### 如何复现

1、添加账号时，账号类型选择“QQ账号”；
2、登录账号。

### 你期望发生的

海豹骰启动gocq时，能跳过5s的启动延迟。

### 实际上发生的

海豹骰启动gocq时，还存在5s的启动延迟。

### 日志文件

![QQ截图20231006201357](https://github.com/sealdice/sealdice-core/assets/101577966/58f9f62a-2055-43b9-8318-f5fa7fd4f15b)

### 海豹核心版本

1.3.0 v20230910

### 操作系统

win10

### 帐号类型

QQ账号

**Comment by MX-fox** [comment]
目前似乎没有对参数启动进行支持吧？

**Comment by Krimiston** [comment]
> 目前似乎没有对参数启动进行支持吧？

有用上`faststart`启动参数，见[gocqhttp_helper.go](https://github.com/sealdice/sealdice-core/blob/060b8f0cabfb99855d3a030087b87bd6260ffda9/dice/gocqhttp_helper.go#L642)。但是目前是“faststart”所以没有生效，应为“-faststart”。
![QQ截图20231006214907](https://github.com/sealdice/sealdice-core/assets/101577966/cad7fb02-885a-490c-a37c-2118f5f8e3fd)
