### ISSUE TITLE
Ui界面滑块支持自行选择自动或者手动

### ISSUE THREAD

**Issue by Director259** [sealdice/sealdice-core#306]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

gocq滑块老炸，ui增加手动可选可以减轻一部分人员分离配置的难度，也一定程度上减少手机豹伤亡

### 有什么好的想法？

在账号配置的时候增加一个选项或者开关，可以提前决定滑块的方式是手动抓取还是自动
或者默认自动提交，但可以在基础设置中自行调整

**Comment by JustAnotherID** [comment]
gocq 停更了，相关需求好像也没有开发的必要了（悲

**Comment by Xiangze-Li** [comment]
@fy0 要不要关掉？
