### ISSUE TITLE
日志按倒序排列并滚动加载

### ISSUE THREAD

**Issue by tme1946** [sealdice/sealdice-core#313]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前后台日志页内容按时间正序加载，查看最新消息需拉到最下方，不够友好

### 有什么好的想法？

1.改为按时间倒序显示
2.改为滚动加载，提高性能

**Comment by MX-fox** [comment]
感觉按时间倒序显示会比较混乱，可以提供拉到底部和回到最上方的按钮

**Comment by MX-fox** [comment]
感觉日志倒叙显示会很混乱，现在已有的 跳转底部快捷键 已经足够了

**Comment by Xiangze-Li** [comment]
骰子的日志是上下文相关的，如果倒序排，就会出现结果在上面而原因在下面的情况，个人感觉与阅读习惯还是不太符合
