### ISSUE TITLE
使用WebDav等对海豹数据库进行备份，或增加数据库配置选项

### ISSUE THREAD

**Issue by PaienNate** [sealdice/sealdice-core#320]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

今天在群内遇到一个倒霉朋友的数据库损毁了，尝试用.dump也导出不了，跑团LOG全部去天堂了（悲）
然后我就想到自己之前摸的一个小记录姬，那个小家伙可以用指令备份到WebDAV中，从而在sqlite崩的时候有备份拿。
或者要不要考虑添加MYSQL等更加安全的数据库呢……？

### 有什么好的想法？

如坚果云目前提供以流量为计算标准的WebDav，添加定时功能将日志对应的文件上传到自己配置的WebDav（比如坚果云）上，可以设置按天或者按小时，这样就能避免损失了吧？

### 其他内容

![image](https://github.com/sealdice/sealdice-core/assets/68044286/43b3c20b-a642-4755-b246-55850ec46440)

**Comment by Xiangze-Li** [comment]
现在已有定时备份功能，虽然无法防止整机损坏导致的数据丢失，但是对于普通的数据库损坏，姑且还是可以保住一部分数据。再接入上传到网络服务，似乎对安全性提高有限？

**Comment by PaienNate** [comment]
> 现在已有定时备份功能，虽然无法防止整机损坏导致的数据丢失，但是对于普通的数据库损坏，姑且还是可以保住一部分数据。再接入上传到网络服务，似乎对安全性提高有限？

有道理！那么我在想，像我遇到的似乎是因为磁盘空间不足导致的数据库损毁，那么是否可以考虑添加磁盘空间到达某个百分比后对骰主进行提示？

**Comment by JustAnotherID** [comment]
> 有道理！那么我在想，像我遇到的似乎是因为磁盘空间不足导致的数据库损毁，那么是否可以考虑添加磁盘空间到达某个百分比后对骰主进行提示？

检查磁盘空间好像不太像是一个骰子应该做的事情……磁盘空间不足的原因如果是自动备份导致的，也许类似「自动备份时仅保留最近的x个备份」的功能更合适？

**Comment by PaienNate** [comment]
> > 有道理！那么我在想，像我遇到的似乎是因为磁盘空间不足导致的数据库损毁，那么是否可以考虑添加磁盘空间到达某个百分比后对骰主进行提示？
> 
> 检查磁盘空间好像不太像是一个骰子应该做的事情……磁盘空间不足的原因如果是自动备份导致的，也许类似「自动备份时仅保留最近的x个备份」的功能更合适？

感觉应该也要关注一下磁盘空间是否快要满了，毕竟对于某些公骰好像……一个数据库大几百M，一个电脑开好几个骰子，一个不注意备份就不够了（大概）

**Comment by Xiangze-Li** [comment]
> > 检查磁盘空间好像不太像是一个骰子应该做的事情……磁盘空间不足的原因如果是自动备份导致的，也许类似「自动备份时仅保留最近的x个备份」的功能更合适？
> 
> 感觉应该也要关注一下磁盘空间是否快要满了，毕竟对于某些公骰好像……一个数据库大几百M，一个电脑开好几个骰子，一个不注意备份就不够了（大概）

ID的意思是, 海豹作为一个骰子核心, 进行磁盘空间检查和内存占用检查有一点"超出本职工作". 我也认同这一观点.

或许可以考虑使用其他第三方的性能监控工具?

**Comment by fy0** [comment]
感觉服务器运维相关是有点超出了，后续加上自动剃毛吧。或者海豹自己统计一下当前自己占用的大小在UI上播报。
issue先关闭了
