### ISSUE TITLE
添加 Satori 协议适配

### ISSUE THREAD

**Issue by fy0** [sealdice/sealdice-core#321]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

再见了，gocq 呜呜
[Mrs4s/go-cqhttp#2471](https://github.com/Mrs4s/go-cqhttp/issues/2471)

### 有什么好的想法？

准备支持
https://github.com/chrononeko/chronocat

同时按照文档说法，考虑Lagrange的golang版本
https://github.com/Linwenxuan05/Lagrange.Core

### 其他内容

![ARCRRZ}(Y75 5MLWCCEMBP7](https://github.com/sealdice/sealdice-core/assets/1579850/0af27d1e-b1c4-45d2-8645-068d33386f1b)

**Comment by JustAnotherID** [comment]
目前（2023.10.10）Chronocat 对 satori 协议的支持还不是很完整，目前还不确定缺少的部分是否影响到骰子依赖的功能，可能同时需要支持 Chronocat 所支持的旧的 red 协议。

**Comment by PaienNate** [comment]
苦露西，对应的项目驾鹤西去了

**Comment by JustAnotherID** [comment]
> 苦露西，对应的项目驾鹤西去了

~~其实是转内部分享，~~普通用户确实用不了了就是了。
不过 satori 协议本身有其他平台的适配，所以还是会做下去的，只是优先级会放低。

**Comment by JustAnotherID** [comment]
先close，感觉这个对接用不太上

**Comment by Xiangze-Li** [comment]
超猫将要打赢复活赛，并且Satori称为新猫唯一指定协议
