### ISSUE TITLE
提供指令添加敏感词功能

### ISSUE THREAD

**Issue by MX-fox** [sealdice/sealdice-core#322]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

**Comment by Xiangze-Li** [comment]
用指令添加敏感词的过程需要把敏感词在IM里发送一遍, 这似乎与敏感词功能的初衷不符了?

**Comment by Szzrain** [comment]
> > 用指令添加敏感词的过程需要把敏感词在IM里发送一遍, 这似乎与敏感词功能的初衷不符了?
> 
> 感觉容易误添加……

我在想的是也许骰主可以发送敏感词的base64编码来添加？但是我想不到这个功能的应用场景

**Comment by JustAnotherID** [comment]
> 用指令添加敏感词的过程需要把敏感词在IM里发送一遍, 这似乎与敏感词功能的初衷不符了?

赞同，而且可能需要回复确认添加的具体敏感词是否正确，更加有风险了。

> 我在想的是也许骰主可以发送敏感词的base64编码来添加？但是我想不到这个功能的应用场景

base64的话一是多了步转换，操作并没有方便到哪去，二是可能会添加错误的词进去，但是进行确认又会导致骰子发送一遍敏感词。

**Comment by JustAnotherID** [comment]
先关闭了，有其他方案再看。
