### ISSUE TITLE
提供检测设备状态功能，并到达设定值时提醒骰主

### ISSUE THREAD

**Issue by MX-fox** [sealdice/sealdice-core#323]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在 #320 中，出现因为硬盘占用爆满导致海豹崩溃，数据丢失的情况。
同时还有诸如内存爆满导致海豹崩溃等其他情况

### 有什么好的想法？

提供检测设备状态功能，比如内存占用，CPU占用和硬盘占用，可指令查询设备状态，并到达设定阈值时提醒骰主

**Comment by fy0** [comment]
在 #320 中后半部分已经有所讨论，基于相同理由issue先关闭
