### ISSUE TITLE
因为敏感词拦截误触发产生的一些需求

### ISSUE THREAD

**Issue by MX-fox** [sealdice/sealdice-core#330]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

敏感词拦截误触发时，骰主难以确实具体是触发了哪一个违禁词

### 有什么好的想法？

1.在后台显示触发违禁词
2.拦截无视CQ码
3.导入的时候忽略空行

**Comment by MX-fox** [comment]
在后台新增显示触发的违禁词，而不只是一整句话

**Comment by JustAnotherID** [comment]
> 2.拦截无视CQ码

可以直接在过滤字符正则里配置 `\[CQ:.+?]` 来无视 CQ 码，默认无视CQ码的话可能会存在使用类似 `[CQ:敏感词汇敏感词汇]` 的方式绕过拦截
