### ISSUE TITLE
没有黑名单记录的账号移出黑名单时候会报错

### ISSUE THREAD

**Issue by MX-fox** [sealdice/sealdice-core#331]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

**Comment by Xiangze-Li** [comment]
已有实现，需要重新确认需求内容

<img width="149" alt="image" src="https://github.com/sealdice/sealdice-core/assets/45380560/46aff03f-e5fa-4acc-99f6-366833e92443">
