### ISSUE TITLE
[Bug]: 钉钉平台log链接生成问题

### ISSUE THREAD

**Issue by Director259** [sealdice/sealdice-core#368]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

钉钉平台log end后未生成链接，后台显示报错，本地文件有日志文件生成

### 如何复现

![3H44}GR2Q{)Y`NC7C%5(B6U](https://github.com/sealdice/sealdice-core/assets/127825341/b51f608d-1deb-4dc4-be35-c193b420efc9)

### 你期望发生的

能发出链接

### 实际上发生的

没有链接生成

### 日志文件

![3H44}GR2Q{)Y`NC7C%5(B6U](https://github.com/sealdice/sealdice-core/assets/127825341/b14ae53e-f30e-49e1-afed-63eeb2c351c0)

### 海豹核心版本

SealDice 231024(dev-65b1)

### 操作系统

win

### 帐号类型

钉钉

**Comment by Szzrain** [comment]
@fy0 
![image](https://github.com/sealdice/sealdice-core/assets/54656633/7d29ac49-985a-4e46-b1bd-62e51b46fd43)

**Comment by Szzrain** [comment]
Should be fixed

**Comment by fy0** [comment]
后端相关的 前几天应该已经修复了，可以试试
