### ISSUE TITLE
master群组可接收send消息

### ISSUE THREAD

**Issue by Director259** [sealdice/sealdice-core#373]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

dodo平台骰子私聊消息需要抓取群组id，导致有些情况下send的内容无法发送到骰主小窗

### 有什么好的想法？

目前支持将群组作为mas添加，或许可以更进一步达成跟小窗一样接收给mas的send消息，这样可以绕开dodo私聊必须抓取群组id的问题

**Comment by Szzrain** [comment]
目前的 send 实现不支持发送到群组，因此我修改此 issue 的标题以匹配其目的
