### ISSUE TITLE
支持反向ws链接

### ISSUE THREAD

**Issue by kagangtuya-star** [sealdice/sealdice-core#379]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

有可作为gocq替代品的[OpenShamrock](https://github.com/whitechi73/OpenShamrock)与[icqq-onebot](https://github.com/lc-cn/onebots)。
OpenShamrock若是稳定低成本部署需要本地使用安卓真机，正向ws链接处于局域网环境的此类设备并不友好；
icqq-onebot不支持正向ws连接，仅支持反向ws链接。

### 有什么好的想法？

建议支持[OneBotV11 或V12](https://12.onebot.dev/connect/communication/websocket-reverse/)的反向 WebSocket

**Comment by Xiangze-Li** [comment]
已通过 #459 实现
