### ISSUE TITLE
[功能建议]跑团日志能否默认为按倒序时间查看，或者增加一个时间排序

### ISSUE THREAD

**Issue by kagangtuya-star** [sealdice/sealdice-core#383]
使用场景可能更多是log丢了找骰主取什么的？
![image](https://github.com/sealdice/sealdice-ui/assets/73411104/a28b203d-5877-473f-8b26-5a8d9299662e)

**Comment by PaienNate** [comment]
顺手给改了，代码忘删了，居然有这个ISSUE？ 现在新版本已经默认按倒序模式查看。
