### ISSUE TITLE
[BUG] 账号设置页「新增账号」按钮展示效果错误

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-core#384]
### 1. 有滚动条时新增账号按钮只有滚动到最下方才显示

<img width="1281" alt="屏幕截图 2023-10-27 114036" src="https://github.com/sealdice/sealdice-ui/assets/45380560/d569c1ec-18c1-4d8d-b253-f2e7ad2cdcab">

<img width="1281" alt="屏幕截图 2023-10-27 114059" src="https://github.com/sealdice/sealdice-ui/assets/45380560/b338be21-78a2-48e2-86a9-8b388229486b">

### 2. 新增账号按钮变形，不再是正圆

见上方图2

**Comment by Szzrain** [comment]
我记着以前没这个问题啊，能找到是哪个版本开始的就好了

**Comment by Xiangze-Li** [comment]
231117(dev-53c2) 按钮形状已经修正为正圆

**Comment by Szzrain** [comment]
哦，第一个还没修？
