### ISSUE TITLE
群管理支持更多平台

### ISSUE THREAD

**Issue by fy0** [sealdice/sealdice-core#398]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

![image](https://github.com/sealdice/sealdice-core/assets/1579850/5b38b0ce-0e85-4f4f-a661-abc0c1b647c6)

### 有什么好的想法？

数据其实是有的，前端忘了添加筛选器

**Comment by Xiangze-Li** [comment]
w，我还以为是别的平台没太大必要管理所以故意去掉了
