### ISSUE TITLE
send 指令发送目标从 master 改为通知列表

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-core#413]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

（from 一云）

**Comment by fy0** [comment]
不能十分确定，因为之前骰主列表和通知列表是刻意做了区分。同时现在群可以作为骰主了

**Comment by Xiangze-Li** [comment]
群作为master这件事只包括权限判断，不包括send目标（捂脸在 2023年11月16日，23:12，fy ***@***.***> 写道：﻿
不能十分确定，因为之前骰主列表和通知列表是刻意做了区分。同时现在群可以作为骰主了
