### ISSUE TITLE
自动清群的已清群组反复通报问题和一些功能性（可选）需求

### ISSUE THREAD

**Issue by Director259** [sealdice/sealdice-core#419]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

自动清群功能目前似乎不会清理群组列表，只是单纯的退出（通知会反复提醒，以及.bot后显示的总群组数量未变），以及缺少一些提醒和可选功能（借鉴自其他骰系

### 有什么好的想法？

1.已经退出的群组不会反复通报（这个大概算bug但一块丢这了）
2.增加可选项-骰子自动退群告别语，骰主可选是否开启或者静默退群
3.增加可选项-免清群列表（或许可以直接借用白名单群列表，使信任群不会被自动清理）

**Comment by kagangtuya-star** [comment]
额外的：
清群的前一段时间提醒被清群，若是继续使用则重新不再清理

**Comment by Xiangze-Li** [comment]
> 额外的： 清群的前一段时间提醒被清群，若是继续使用则重新不再清理

不现实: 提醒被清理群 这个动作会导致目标的最后使用时间被刷新

**Comment by Xiangze-Li** [comment]
最重要的重复通报问题已解决，剩余问题另开 Issue 跟踪.
