### ISSUE TITLE
重构 Dice 类

### ISSUE THREAD

**Issue by Szzrain** [sealdice/sealdice-core#431]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

现在的 Dice 类已经变成了一个屎山，掺杂了过多的配置项，应当将这些配置项提取出来单独管理

### 有什么好的想法？

我在 #333 设计了 ConfigManager 其目前用于 JS 的插件配置项，但是也完全可以胜任内部配置项的管理，我目前的想法是将 Dice 类中大部分的配置项都迁移到一个新的 ConfigManager 以方便管理和维护

**Comment by Xiangze-Li** [comment]
\Szz/

非常需要. 往屎山上拉屎实在是过于罪恶.

**Comment by Szzrain** [comment]
经过商议，`ConfigManager` 作为动态配置管理器有些没必要且不适合，目前商议的方案是定义一个新的 `Config` struct 并将配置项都放在这个里面

**Comment by Xiangze-Li** [comment]
默认值应当单独写在一个文件里, 它的内容类似: 

```go
package config

var DefaultConfig = Config{
    // default values
}
```

**Comment by Xiangze-Li** [comment]
添加配置项的人应当负责维护 migration. 

维护一个独立的版本序号, 在需要添加 migration 时增加这个序号.

**Comment by JustAnotherID** [comment]
可能得同步重构 UI 中的设置部分

**Comment by Xiangze-Li** [comment]
进入 nightly 试吃！
