### ISSUE TITLE
自动清群时支持发送告别语

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-core#440]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

考虑加一条文案, 自动退群时取出使用, 留空即为静默.

**Comment by Xiangze-Li** [comment]
Ref #419

**Comment by Szzrain** [comment]
经过初步检查，#443 可能存在问题，在此reopen此issue，详细情况已在 #443 的 conversation 中提出

**Comment by Xiangze-Li** [comment]
已经修改
