### ISSUE TITLE
[Bug]: Dc-like 平台 dismiss 后再拉入处于 bot off 状态

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-core#447]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

在 KooK 和 DoDo 复现，Dc Tg 未确认。

### 如何复现

dismiss 再拉入，bot 检查开启情况

### 你期望发生的

拉入后处于开启状态

### 实际上发生的

关闭

### 日志文件

N/A

### 截图

N/A

### 海豹核心版本

Dev

### 操作系统

N/A

### 帐号类型

N/A

### 附加内容

from 仓鼠

**Comment by Szzrain** [comment]
我建议直接移除 dismiss 后会自动 bot off 的机制

**Comment by fy0** [comment]
#474
