### ISSUE TITLE
[Bug]: 测试版本qq端非官bot协议戳一戳不响应

### ISSUE THREAD

**Issue by Director259** [sealdice/sealdice-core#454]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

gocq可接受戳一戳，但海豹未回应，后台基础设置确认开启戳一戳并且没有存在空白戳一戳

### 如何复现

更新231129(dev-0a94)测试版

### 你期望发生的

能回应戳一戳

### 实际上发生的

未回应戳一戳

### 日志文件

![0H1)W _D$QAJEG5@~{R(H G](https://github.com/sealdice/sealdice-core/assets/127825341/574ea18f-cd1c-46ca-953e-65d51b643565)
![J~FFPBCT}4N`C1`YOIY@J_L_tmb](https://github.com/sealdice/sealdice-core/assets/127825341/d641f699-49dd-49b5-9a3a-619a39790448)

### 海豹核心版本

SealDice 231129(dev-0a94)

### 操作系统

win分离部署，使用海豹内置gocq

### 帐号类型

qq

### 使用协议

分离apad，正向ws

**Comment by Szzrain** [comment]
不响应应该是没有这个事件，等以后腾讯官方API出了这个事件再说吧

**Comment by JustAnotherID** [comment]
木落佬修复了，但没有pr关联不了，手动关闭
