### ISSUE TITLE
DoDo 平台对接消息撤回事件

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-core#470]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

**Comment by Xiangze-Li** [comment]
from 仓鼠

**Comment by Szzrain** [comment]
![IMG_0092](https://github.com/sealdice/sealdice-core/assets/54656633/c41fc02e-c430-49b0-8503-59b3766727d1)
哈哈，想不到吧，我们先进的 `DoDo` 压根没有撤回消息事件捏

**Comment by Szzrain** [comment]
unable to solve, close instead.
