### ISSUE TITLE
JS插件Api请求：在指定消息环境下运行输入的指令，并返回结果

### ISSUE THREAD

**Issue by kagangtuya-star** [sealdice/sealdice-core#475]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

用于较为安全地以插件形式实现梨骰的自定义命令宏功能。

### 有什么好的想法？

api输入参数：（ctx，命令）
api返回值：命令执行的结果

如在一个群组执行“。rd20”或“。team call 小队”，海豹核心在对应群组隐式执行一次（不返回结果），并在api中返回执行完成的回复语

**Comment by oissevalt** [comment]
涉及到数据改动的指令（比如人物卡），如果没有显示回复，是不是会引起迷惑

**Comment by Xiangze-Li** [comment]
> 涉及到数据改动的指令（比如人物卡），如果没有显示回复，是不是会引起迷惑

或许可以将**执行的指令**回显，让用户对于变化有所预期。**指令输出**可能较长，略去是可以的。

**Comment by Szzrain** [comment]
返回指令执行结果的说法不太明确，如果指的是骰子发送的消息的话可能不太容易实现，因为现在的插件是通过调用 `seal.replyToSender` 来发送消息，如果按照目前的 API 来看，返回的只会是一个 commandExecuteResult

**Comment by kagangtuya-star** [comment]
之前并未说清楚（以及邮件回复漏了）

应该是
api输入参数：（ctx，命令）
api返回值：命令执行的结果

如在一个群组执行“。rd20”或“。team call 小队”，海豹核心在对应群组执行一次，并返回执行完成的结果

**Comment by Xiangze-Li** [comment]
以「快捷指令」或「别名」的指令形式提供（Ref #489）。

考虑到作弊使用的危险性，不暴露此 API。
