### ISSUE TITLE
[Bug]: 后台群组管理群名「未获取到」

### ISSUE THREAD

**Issue by Director259** [sealdice/sealdice-core#477]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

后台群组管理无法获取正确群名，通知也一直是<%未知群名%>

### 如何复现

更新有问题的测试版本

### 你期望发生的

跟以前一样能够显示正确的群名

### 实际上发生的

「未获取到」
![KDHBGZ4{D`{YT27S5 M`M9N](https://github.com/sealdice/sealdice-core/assets/127825341/22876a5f-9ab5-4c71-8e47-14f8b2484dbe)

### 日志文件

早上经过测试应该在11.22之后的dev版本之后出现问题

### 海豹核心版本

231129(dev-0a94

### 操作系统

win

### 帐号类型

qq

### 使用协议

apad,ws正向分离

**Comment by Xiangze-Li** [comment]
二分测试了一下，是这 5 个 commit 引起的。
