### ISSUE TITLE
部分指令，例如.nn没有 .nn help 多见于早期指令

### ISSUE THREAD

**Issue by fy0** [sealdice/sealdice-core#482]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

**Comment by Xiangze-Li** [comment]
占楼：我会对现有指令是否有 help 子指令进行统计。

**Comment by fy0** [comment]
在sealchat可以逐个调查，目前版本（143dev）
![image](https://github.com/sealdice/sealdice-core/assets/1579850/1f2d07c6-26b3-4b82-8fcb-e2482732be6e)

已测试文字头：A B C D E F G H I J L M N O P Q R S T U (全部完成，未列出的是没有)

C: coc、cra
D: dismiss、dnd、drl
E: ekgen、en、ext
F: find fox
G: gugu
H: help hiy
J: jrrp jsr
L: li
N: nn
P: ping
R: r ra ri(有help但有点问题) 
S: sc 
T: text ti
U: userid
