### ISSUE TITLE
群组管理应该支持更多平台

### ISSUE THREAD

**Issue by fy0** [sealdice/sealdice-core#483]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

![image](https://github.com/sealdice/sealdice-core/assets/1579850/47c7f406-8875-4ee7-918e-813bae99c004)

### 有什么好的想法？

实际上api里可能给了数据，前端这块没有跟上。。

**Comment by Xiangze-Li** [comment]
Duplicate #398
