### ISSUE TITLE
指令提案: 快捷指令 .quick

### ISSUE THREAD

**Issue by fy0** [sealdice/sealdice-core#489]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

-

## 摘要

对于星尘提出的，参考梨骰 .define 实现一个类似的海豹指令的想法，本文旨在提出一种具有类似功能，对跑团有所帮助，同时低耦合度的实现方式。

## 背景

梨骰的.define的实现与C中的宏完全相同，是基于文本替换的实现方式，同时在单次替换完成后会迭代替换，直到完成所有替换。同时，梨骰宏的使用范围是单用户跨群，也就是同一个用户定义的宏可以自己在任意群使用，而其他用户无法借用该用户定义的宏。此外，梨骰的宏具有最高优先级，即在指令解析进行之前，允许使用宏覆盖现有指令。

对于海豹来说，宏实现的优缺点我们在使用C的时候都已经充分品鉴过了，开发组认为不应引入宏机制。
因此采用了bash中alias（别名）的思路，第一版本实现为这个PR #488 
这个PR总体保持了与梨骰类似的思路，单用户跨群，高优先级，但是限制了`快捷指令`(也就是梨骰中的宏，下同)必须是一个指令，提高了安全性。

基于这一版实现，再次引发了开发组的讨论，主要集中的点是：
* 快捷指令会创建出新指令，这会造成用户混淆普通指令和快捷指令
* 作为新增的非核心功能，却会改变底层框架行为，并与之深度耦合
* 其他玩家分不清快捷指令用户究竟骰了什么
* 快捷指令的高优先级导致存在灌铅可能

经过讨论后，现提出第二版草案

## 指令说明

指令：.quick
可用别名：`.&`  `.q`
使用范围：群内成员共同可用，或限制群内管理员可新增，成员可执行
作用：为一个现有的完整骰点指令制作一个快捷方式，使其可以一键执行

指令表：
#### .q add <快捷指令> <映射到指令>

举例：.q add 摸箱子  .draw xx地区1-5级宝箱-武器类型

kp: .q add 摸箱子  .draw xx地区1-5级宝箱-武器类型
骰: 已新增快捷指令: 摸箱子
kp: 于是怪物倒下了，你们搜查了他的巢穴，发现了几个箱子，现在摸箱子罢（pc输入 .q 摸箱子）

pc: .q 摸箱子
骰：
[快捷指令 .draw xx地区1-5级宝箱-武器类型]
抽取到 [锋利的剑]

### .q list
查看现有的快捷指令

### .q rm/del <名字>
删除一条快捷指令

### .q <快捷指令>
执行快捷指令
可以使用另一个用法， `.&快捷指令`

### 参数

我们设定临时变量，$t0 为全部的参数，从$t1开始是变量的分割，如
.q 快捷 aaa bbb ccc
$t0: aaa bbb ccc
$t1: aaa
$t2: bbb
$t3: ccc

于是可以使用：
.q add 前期怪物 .draw .drawXX地区1-3级怪物-人形怪  {$t1 || 3}

kp(备团): .q add 前期怪物 .draw XX地区1-3级怪物-人形怪 3
kp: 于是你们踹门进去，忽然门外来了一辆面包车，车上下来一些人，直接冲你们杀过来
kp: .r 2 + d5 人数
骰: 由于人数，2+d5 = 4
kp: 车上下来四个人
kp: .q 前期怪物
....

### 总结

如此实现的话，指令不需要修改骰子的全局机制了，也能明确快捷指令和普通指令的区别
同时可以大胆进行扩展，使其功能变得更强

**Comment by JustAnotherID** [comment]
比起使用 `quick`，更倾向于直接用 `alias`，后者是此类功能的通用称呼。

**Comment by fy0** [comment]
> 比起使用 `quick`，更倾向于直接用 `alias`，后者是此类功能的通用称呼。

原则上都可以，看大家倾向于什么词

**Comment by Xiangze-Li** [comment]
quick 含义是不明显的。它只表示了「快捷」，但无法体现是与指令有关。
