### ISSUE TITLE
同一个海豹的账号默认有botlist

### ISSUE THREAD

**Issue by fy0** [sealdice/sealdice-core#49]

**Comment by Xiangze-Li** [comment]
同一海豹后端的多个账号在同一个群中的情况, 或许在骰主的测试群中才更常见. 在这种时候或许有骰主登录一个小号来进行测试的需求. 如果互相有botlist, 会造成无法使用登录为海豹账号测试另一个海豹账号的问题.

**Comment by Xiangze-Li** [comment]
@fy0 需要重新讨论需求合理性

**Comment by fy0** [comment]
明白了，那或者就是提供更便利的添加方式，或者是更拟真的测试环境
