### ISSUE TITLE
[Bug]: 非 CoC 规则不能用 intGet 或 format 读取“魔法”属性

### ISSUE THREAD

**Issue by oissevalt** [sealdice/sealdice-core#490]
1. 切换到非 CoC 规则；
2. 使用 JS 中 `seal.format` 和 `seal.vars.intGet` 取得“魔法”，失败，其中 `intGet` 返回 `[0, false]`，认为该属性不存在；
3. `text` 和 `st show` 均能获取其值；
4. 其他 CoC 内置属性能被 JS 读取，证明不存在普遍的名称冲突。

系统：Windows 10 21H2 (x64)
版本：1.4.2

**Comment by fy0** [comment]
seal.vars.intGet： 因为这个函数底层只读取人物属性，不涉及规则模板，因此没有读到预置变量

**Comment by fy0** [comment]
行为符合预期，先关闭了
