### ISSUE TITLE
[Bug]: 仅限于 gocq 适配器，在未初始化的群中触发“戳一戳”事件时报错

### ISSUE THREAD

**Issue by f44r** [sealdice/sealdice-core#499]
如题，原因是

https://github.com/sealdice/sealdice-core/blob/2b6335cdd5a5f8e010a2ce564078865ba742c5f9/dice/im_helpers.go#L117-L119

如果未获取到 GroupInfo 直接返回 nil，而在 packTempCtx 中并没有做 nil 检查

https://github.com/sealdice/sealdice-core/blob/2b6335cdd5a5f8e010a2ce564078865ba742c5f9/dice/platform_adapter_gocq.go#L1264

**Comment by FlameTEXT** [comment]
本来想在这里补上初始化的逻辑，但是发现一个久远的 TODO

https://github.com/sealdice/sealdice-core/blob/2b6335cdd5a5f8e010a2ce564078865ba742c5f9/dice/platform_adapter_gocq.go#L542-L543

不太熟悉这里的逻辑，担心直接修改出问题，目前倾向于打个日志后不再继续执行就算 fix 了
