### ISSUE TITLE
[BUG] pcdel导致的角色卡无法解绑和删除

### ISSUE THREAD

**Issue by CodeCrow777** [sealdice/sealdice-core#51]
绑定角色卡时，pc del留空默认用玩家名检索角色，如果成功检索到未绑定的角色卡，会：
◆删除对应角色
◆清除群内空白卡
◆解除当前群绑定状态，启用群内空白卡
◇原先绑定角色会变为★（绑定信息有当前群，但当前群却不是绑定状态）
出现◇的情况后，如果再去绑定另外一张角色卡。
会出现[错误显示★的角色卡]无法用pc untagall解绑，同时也无法用pc del删除的情况。
——————————————
【复现步骤】
1.准备三张未绑定的角色卡
2.pc tag绑定第一张
3.nn 更名为第二张
4.发送[pc del]
5.pc tag绑定第三张

此时第一张会变成[错误显示★的角色卡]，无法用pc untagall解绑，也无法用pc del删除

**Comment by ChunChong777** [comment]
更新了，但bug还在
![Uploading QQ图片20231015045942.png…]()

**Comment by Fripine** [comment]
按照复现步骤实现到第5步后，此时绑定的是第三张卡，第一张卡成为★角色卡无法使用pc del删除，若此时再使用pc tag切换到第一张卡，然后再pc tag切换到第三张卡，此时可以正常使用pc del删除第一张卡。
看了具体代码后有一点很疑惑，“核心:角色管理_删除成功_当前卡”这个词条提示“由于你删除的角色是当前角色，昵称和属性将被一同清空”，如果一张卡在被绑定的状态下需要解绑才能删除，那为何会提示你可以删除当前正使用的角色卡？

**Comment by fy0** [comment]
人物卡系统和pc指令进行了重做，重新进行尝试
