### ISSUE TITLE
[Bug]: CoC难度等级检定大失败判定不符合规则书

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-core#525]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

根据规则书，大失败的范围是根据「成功需要的点数」而不是「技能值」。

即，如果一个技能在 50 以上，但半值在 50 以下，在进行困难难度的检定时，应该根据半值，将 96-100 都判定为大失败。

参考以下规则书截图（来源：守秘人规则书 40 周年版，中译 Build 2210，第 90 页）

![IMG_0429](https://github.com/sealdice/sealdice-core/assets/45380560/2fabe20d-a547-4d61-b07f-589b4e529dcb)

### 如何复现

`.ra (96) 困难侦查80`

### 你期望发生的

大失败

### 实际上发生的

普通失败

### 日志文件

NA

### 海豹核心版本

142+dev

### 操作系统

NA

### 帐号类型

NA

**Comment by fy0** [comment]
#527

**Comment by Xiangze-Li** [comment]
Followup #527 

没有彻底修复。在原始技能值高过出目时仍不能正确判定。

```txt
$ .ra (96) 困难侦查99
（没有大失败：不符合预期）
$ .ra (96) 困难侦查95
（大失败：符合预期）
```

**Comment by Xiangze-Li** [comment]
等待确认效果
