### ISSUE TITLE
[Request/Improvement] 优化JS插件重载流程方便调试 

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-core#53]
调试插件时，完成编辑后需要先到WebUI的插件管理重载JS再到指令测试或QQ群测试效果。这样就需要在编辑器、WebUI、QQ群三个窗口之间切换。

因此，我希望能够优化插件重载流程，将切换的窗口数减少到两个。

我目前设想了两个可能的实现方法：

1.  在WebUI的指令测试页面增加一个「重载JS」按钮，功能与插件管理页面一致即可；这样实现，测试时只需在编辑器和WebUI切换；
2.  增加一个重载插件命令，功能与牌堆的 `draw reload` 类似；这样实现，测试时只需在编辑器和QQ群切换。

请考虑支持，优化一下插件开发体验。

**Comment by JustAnotherID** [comment]
ui和命令都提供了
