### ISSUE TITLE
[Bug]: QQ官方机器人接入海豹端后,QQ频道内尝试使用对应指令无效,且日志栏报错 

### ISSUE THREAD

**Issue by UnicornXR** [sealdice/sealdice-core#530]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

在使用官方QQ机器人接入海豹端后，在QQ频道内尝试使用对应指令完全无效 日志栏报错。

### 如何复现

填入QQ官方生成的机器人ID、令牌与秘钥后，机器人添加成功并在数秒后显示连接成功，随即我个人创建了一个频道将机器人邀入频道内 测试任意指令，无反应且后台报错，即便是没有发送消息每间隔几秒也会出现报错。

### 你期望发生的

正常显示我在QQ频道内所发出的消息并做出对应的回复。

### 实际上发生的

机器人无反应，不论频道内发送什么命令日志均无显示只显示报错

### 日志文件

[record.zip](https://github.com/sealdice/sealdice-core/files/13854316/record.zip)
可能会有些乱，这个是我在日志里截出来的
![QQ图片20240108013044](https://github.com/sealdice/sealdice-core/assets/106969060/61f61bf5-3a0a-4b60-a736-55d59cdf3a9e)
希望能帮助你

### 海豹核心版本

1.4.2 v20231210

### 操作系统

win10

### 帐号类型

一个QQ群用的骰子号以及一个使用QQ官方机器人协议并已连接海豹的QQ频道机器人，QQ频道机器人在AT它发送指令后无反应，且日志报错
![QQ图片20240108010835](https://github.com/sealdice/sealdice-core/assets/106969060/8bd6e043-cd2a-480d-9c94-4485fed28e01)
左侧为QQ官方机器人 右侧为群内骰子号

**Comment by fy0** [comment]
群内功能正常吗？只是频道报错？

**Comment by fy0** [comment]
似乎是这样一种情况：当开放平台只有频道而没有群的时候，会出现这种情况

**Comment by UnicornXR** [comment]
群内功能正常，频道那边日志完全看不见我发的消息，只是在复读那个报错

**Comment by UnicornXR** [comment]
QQ官方的机器人 个人只让进频道不让进群呀...这种情况下岂不是死结了
