### ISSUE TITLE
开放海豹跑团日志记录对接第三方后端上传服务

### ISSUE THREAD

**Issue by PaienNate** [sealdice/sealdice-core#539]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

或许有用户需要对接自实现的日志上传系统和染色器。以实现差异化，保证稳定性……（心虚）

### 有什么好的想法？

由于一直没有人做，所以自己摸了一个出来，算是抛砖引玉：其基于Cloudflare Worker的日志后端系统，并且借助Vercel部署自定义的染色器，能做到差异化。地址：https://github.com/PaienNate/cf_sealdice_logbackend ，在配置得当的情况下或许可以减轻服务器的压力。
目前是尝鲜状态，会不定期更新，协议使用MIT，可以随便用。

### 其他内容

https://myseal.firehomework.top/?key=OYCo#401356 可以在此处查看我测试搭建的日志（染色器 + 后端）。

**Comment by JustAnotherID** [comment]
感觉可以搞，不过类似的设置应该和普通的设置项区分开，UI上应当增加类似「高级设置」的页面。
而且设置项这块在重构，是排在 v1.5 比较合适吗？🤔

**Comment by Xiangze-Li** [comment]
> 感觉可以搞，不过类似的设置应该和普通的设置项区分开，UI上应当增加类似「高级设置」的页面。 而且设置项这块在重构，是排在 v1.5 比较合适吗？🤔

挂着慢慢做呗（
