### ISSUE TITLE
[feature request] JS 插件支持操作黑名单

### ISSUE THREAD

**Issue by Szzrain** [sealdice/sealdice-core#542]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

因为一些特别的需求，有用户希望可以允许 JS 插件能够读取和添加新的黑名单用户

### 有什么好的想法？

seal.black.edit(ctx, 怒气值, 原因)
seal.black.list()
seal.black.find(ctx)
暂时的想法是这样，具体参数仍待商榷

**Comment by Xiangze-Li** [comment]
操作黑名单需要传入 MsgContext 吗？
