### ISSUE TITLE
[Bug]: JS getIntConfig 时报错

### ISSUE THREAD

**Issue by Szzrain** [sealdice/sealdice-core#546]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

插件注册了类型为 Int 的配置项后，在 UI 中修改配置项的值，随后在代码中调用 seal.ext.getIntConfig 后报错

### 如何复现

![image](https://github.com/sealdice/sealdice-core/assets/54656633/1b39d7e4-f2c6-436f-ab59-f98df9f303d7)

1. 使用 `seal.ext.registerIntConfig()` 注册一个整数配置项
2. 在 UI 中修改此配置项的值
3. 调用 `seal.ext.getIntConfig()`
4. 错误产生

### 你期望发生的

返回正常的配置项

### 实际上发生的

报错
interface conversion: interface {} is float64, not int64

### 日志文件

![image](https://github.com/sealdice/sealdice-core/assets/54656633/719f0af6-f6ef-43c8-b659-c9eabe4c55d8)

### 海豹核心版本

SealDice 1.4.3f1 v20240110

### 操作系统

Windows

### 帐号类型

无关

**Comment by Szzrain** [comment]
目前猜测为前端传回的数据类型为浮点数导致的类型变化

**Comment by Szzrain** [comment]
也有可能是 interface{} 默认的数字类型为 float 导致

**Comment by Szzrain** [comment]
疑似依然能复现此 bug，先 reopen

**Comment by Fripine** [comment]
> 疑似依然能复现此 bug，先 reopen

再次复现流程：修改UI配置项中的值并点击保存，此时调用 seal.ext.getIntConfig 不会报错，但单击 重载JS 按钮后，再次调用 seal.ext.getIntConfig 出现报错
![a69bda88279e9a926649f74e8e560046](https://github.com/sealdice/sealdice-core/assets/84258717/b499db0e-eff5-4385-b551-92d7676ec940)
