### ISSUE TITLE
DnD 插件增补自定义文案支持

### ISSUE THREAD

**Issue by AArson1st** [sealdice/sealdice-core#551]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

rc指令無法自定義，以及優勢劣勢骰無法讀取繁體的問題

### 有什么好的想法？

增加rc指令「<角色名>的“屬性”检定(dnd5e)结果为:」這個部分的自定義
或許可以新增.rc 优势 <表达式>骰能以.rc 優勢 <表达式>響應的功能

當然如果能增加天命骰點時前墜後墜「<角色名>的DnD5e人物作成(自由分配模式):」、「获取带属性名的预设请用.dndx」這部分的自定義就更好了

### 其他内容

![image](https://github.com/sealdice/sealdice-core/assets/158039994/59d5b312-cfea-45b0-ab47-ea16854d928c)
![image](https://github.com/sealdice/sealdice-core/assets/158039994/b5329512-89cb-4309-b923-6e633c82897c)

**Comment by oissevalt** [comment]
简体的优势/劣势好像写死在 peg 文件里了，木落来看一下 @fy0

**Comment by Xiangze-Li** [comment]
在 dnd 插件的 `rc` 指令中，也就是本 Issue 所提出的这个场景下，支持使用 優勢/劣勢 了。在 `r` 的算式中由于没有搞清 PEG 生成，尚不能支持。

文案的自定义留待下一步开发。

**Comment by Szzrain** [comment]
目前可以使用 `.r d20kh` 和 `.r d20kl` 来代替 优势/劣势 的使用

**Comment by fy0** [comment]
准备在1.4.5进行处理

**Comment by Xiangze-Li** [comment]
#690 只处理了 r 指令的繁体「优势/劣势」，尚未实现 DnD 插件的自定义文案。目前不应关闭。

**Comment by kenichiLyon** [comment]
制卡的自定义文案已在后端提交pr #1002 
由于本人对 DnD 研究不深，故只对此项fix。
