### ISSUE TITLE
[Bug]: 使用拉格兰分离部署无法回复私聊指令，并且将所有人私聊视为同一群组

### ISSUE THREAD

**Issue by YuSheng133** [sealdice/sealdice-core#562]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

在使用Lagrange分离部署时，骰子对于私聊指令会在日志中显示已经回复，但指令发送者无法看到消息。暗骰和send引起的回复似乎可以正常发送；如果有任意发送者在私聊中发送了.set dnd，似乎其他人的指令回复也会由coc切换到dnd。在海豹官群中发现该现象似乎不止仅在测试版发生。

### 如何复现

使用7.0 .net sdk 和[拉格兰](https://github.com/LagrangeDev/Lagrange.Core/actions/runs/7667149334)分离部署，在海豹账号设置中填入onebotv11分离部署账号和地址，私聊发送指令

### 你期望发生的

骰子应当能够正常发送私聊反应，并将不同账号的私聊分别回应

### 实际上发生的

骰子在日志中显示正常回复了私聊，但指令发送方和登陆了骰子账号的真设备qq均无法看到消息。

### 日志文件

![286dcde85e54a7e2eacc840537c94c19](https://github.com/sealdice/sealdice-core/assets/98568467/7262ff5f-087b-4138-9c6f-76aeda6792f3)

### 截图

![a2423d4c5e829adcf8485af49105285e](https://github.com/sealdice/sealdice-core/assets/98568467/5807f6ce-22dc-44a6-a25b-5cbb9f5c5317)
<img width="682" alt="截屏2024-02-02 19 04 50" src="https://github.com/sealdice/sealdice-core/assets/98568467/ffb51939-9442-4759-8083-14a611f5deac">
<img width="210" alt="截屏2024-02-02 19 05 03" src="https://github.com/sealdice/sealdice-core/assets/98568467/075fa966-dfb3-4541-9b06-fd0be54bfd57">

### 海豹核心版本

SealDice 240201(dev-04fb)

### 操作系统

Windows

### 帐号类型

QQ(Onebot11分离部署，拉格兰框架)

**Comment by PaienNate** [comment]
昨天在群友的怂恿下研究了一下这个东西。基于Onebot11的设计来说：
[https://github.com/botuniverse/onebot-11/blob/master/event/message.md](url)

> 需要注意的是，sender 中的各字段是尽最大努力提供的，也就是说，不保证每个字段都一定存在，也不保证存在的字段都是完全正确的（缓存可能过期）。

拉格兰部署无法发送信息，根本原因是拉格兰并没有提供Sender字段，Sender字段是完全空白的。Go-cqhttp的API声明Sender字段与Onebot11不同，它并未声明sender字段是尽最大努力提供，或许”Go-CQHTTP会直接提供sender字段并保证其存在"。

由于本人并没有完全研读该项目，所以我只进行了一点小改动，不适合提PR。我的修改方法为：在platform-adapter-gocq.go中，996（嗯？996！）行后添加：
```go
			if msgQQ.MessageType == "private" {
				fmt.Println(string(msgQQ.SelfID))
				if msg.Sender.UserID == "QQ:" {
//如果Sender中的UserID不完整，从消息中解析用户ID并拼接
					msg.Sender.UserID = "QQ:" + string(msgQQ.UserID)
				}
//设置一个默认的私聊名称
				if msg.Sender.Nickname == "" {
					msg.Sender.Nickname = "（骰子旋转中…）"
				}
			}
```

由于目前尚不清楚nickname的获取方式，期待更好的解决策略。
同时它也会解决私聊测试骰子时没能获取到名称的问题（比如下面这样的）（废话都默认赋值了）
![image](https://github.com/sealdice/sealdice-core/assets/68044286/b3f52fdd-2d81-4461-a219-9582363010e5)

关于.set dnd的问题，我捋了一下是不是这么个意思：

骰子虽然私聊并没有发出去，但是日志里显示它在发送消息；且当A用户设置.set dnd后，B用户私聊骰点时，虽然没有收到消息，但根据日志来看，消息实际上也已经转换成了dnd的格式？

如果是这样的情况，那么问题实际上是同一个问题：因为默认不存在的ID似乎初始值是0，又因为没能获取到用户ID，那么所有私聊的用户ID在海豹看来都是0.

怎么解决，是拉格兰单开一个连接还是从gocq上进行修改，或许老牌的开发者们比我更清楚。毕竟我只是提交了一个改错字的pr（喂！）

另外：大过年的，各位新年快乐。
