### ISSUE TITLE
[Feat Req] `log-export` 目录导出的 zip 支持从 WebUI 下载和删除

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-core#565]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

Ref #512 

给导出的 Log zip 文件添加一个类似当前 **备份** 的 WebUI 页面，支持从网页下载和删除，同时支持配置自动清理。

合理性：对于服务器部署，尤其是 Linux 服务器部署，在服务器和本地之间传输文件是比较麻烦的。如果能通过 WebUI 直接下载则方便很多。

**Comment by PaienNate** [comment]
感觉可行，另外作为第三方后端开发者问一嘴：如果以后有了第三方后端，是否有必要提供后端迁移的服务？或者说”重新上传“到另一个服务器的服务？

**Comment by Xiangze-Li** [comment]
> 感觉可行，另外作为第三方后端开发者问一嘴：如果以后有了第三方后端，是否有必要提供后端迁移的服务？或者说”重新上传“到另一个服务器的服务？

你所讲的需求从逻辑和实现角度都是可行的，但是不应该和这个 WebUI 需求合并，可以考虑挂在之前那个对接第三方服务器的需求下面？
