### ISSUE TITLE
[Refactor]: 需要重构 IMSession.ServiceAtNew

### ISSUE THREAD

**Issue by Szzrain** [sealdice/sealdice-core#588]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

IMSession.ServiceAtNew 依靠一个kv map维护 GroupInfo，首先，这个名字很反直觉，第一时间想不到是干啥的，其次，这种数据结构已经无法完全满足海豹的需求。即一部分平台（例如 Discord）分为服务器（Guild）下属子频道的模式，但是并没有一个存储Guild信息的地方

### 有什么好的想法？

建议重构所有与 IMSession.ServiceAtNew 相关的引用，并且使用新的数据格式来存储群组数据

**Comment by Xiangze-Li** [comment]
duplicate #869
