### ISSUE TITLE
拦截日志分页或部分删除需求

### ISSUE THREAD

**Issue by Director259** [sealdice/sealdice-core#602]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前的拦截日志会记录该功能开启以来全部的内容，导致该页变得非常的长，需要查看最新记录的时候有些难找

### 有什么好的想法？

增加类似日志管理的分页，或者可以选择性删除一定时间内的拦截记录

**Comment by fy0** [comment]
有道理，可以加入todo中
