### ISSUE TITLE
为。nn指令提供代骰功能

### ISSUE THREAD

**Issue by kagangtuya-star** [sealdice/sealdice-core#605]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

部分玩家会忘记修改自己的名字，特别是秘密团拉新群时。

### 有什么好的想法？

为。nn指令提供代骰功能
例如。nn 测试 @对应目标

将被@者的名字修改

### 其他内容

无

**Comment by Xiangze-Li** [comment]
需要考虑滥用风险

**Comment by Szzrain** [comment]
我不赞同实现这个feature
