### ISSUE TITLE
[Imp]: WebUI Log 预览使用更方便阅读的颜色

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-core#624]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前 WebUI 中的 Log 预览使用了随机的颜色来区分不同发言者。有些随机生成的颜色较难以阅读。

### 有什么好的想法？

人工选择若干种容易阅读又有区分度的颜色。在发言者数量不大于预选颜色时直接分配使用。

如果发言者数量大于预选颜色数量，超出的部分仍然可以随机生成。也可考虑将随机范围做一定限制。

**Comment by PaienNate** [comment]
这让我想起来一个库，或许有参考价值：https://randomcolor.lllllllllllllllll.com/

**Comment by Xiangze-Li** [comment]
效果不尽如人意，仍会出现太淡的颜色，并且有重复颜色

![image](https://github.com/sealdice/sealdice-core/assets/45380560/de49454d-2d90-4535-b8d1-49f1b4b2a8f4)
