### ISSUE TITLE
DND功能完善以及屬性同義詞

### ISSUE THREAD

**Issue by AArson1st** [sealdice/sealdice-core#631]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

DND不同翻譯組規則的慣用翻譯屬性同義詞無法互相連同。

以及體質屬性在繁簡轉換上似乎有問題？
![image](https://github.com/sealdice/sealdice-core/assets/158039994/d601bc27-85bf-4fc2-a9ba-f9ca60836731)

### 有什么好的想法？

新增部分繁體翻譯組慣用的繁簡同義詞連通
使用翻譯資料連結：[5etool](https://5etools.wayneh.tw/5etools.html)、[5e自動角色卡](https://docs.google.com/spreadsheets/d/15eWVfzgA57tcxpbP4izt42RXozGgJpYQ87HFGjqC9-Q/edit#gid=2050592502)
> 屬性「体质」新增同義詞：體魄、体魄
> 技能「体操」新增同義詞：特技動作、特技动作
> 技能「巧手」新增同義詞：上手把戲、上手把戏
> 技能「驯兽」新增同義詞：動物馴服、動物馴養、动物驯服、动物驯养
> 技能「洞悉」新增同義詞：察言觀色、察言观色

體質屬性或許再麻煩確認繁簡的關鍵字連通是否有問題？（如上方附圖）其他屬性使用繁體輸入`.rc 屬性豁免`檢定都是沒問題的，只有體質沒辦法正確擲骰。

**Comment by fy0** [comment]
今天是发版日，再晚几个小时就错过了
