### ISSUE TITLE
请求删除"遭遇风控时自动重登录"功能，或调整为只允许手表用户在账号设置中启用。

### ISSUE THREAD

**Issue by ShiaBox** [sealdice/sealdice-core#637]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

"遭遇风控时自动重登录"功能导致很多骰主在不了解当前情况，或者以为可以获得正向收益的情况下开启。
开启后，当qsign签名失败的情况下出现风控时，会自动重新登陆并重新生成设备信息，从而导致以下情况发生：
1.当协议高于8.9.83时，需要在备份里换回旧的设备信息然后重新滑块，在当前环境下，滑块对于计算机属性较低的用户来说是一个相对有困难的操作。
2.当协议原本为8.9.70等不会封号的协议时，会导致直接触发”旧设备+新设备信息“的情况，极端案例下会导致触发版本陷阱，必须使用高版本协议，降低稳定性。

不管哪种情况，都会导致原本只需要重启qsign的操作变得复杂且繁琐。

### 有什么好的想法？

所以，基于以上情况，建议在后续版本中移除此过时功能，或者将其移动至账号设置-添加账号-手表协议登录的子选项中。

**Comment by kenichiLyon** [comment]
对于删除功能来说，我个人更倾向于这个开关设置成常态关闭，有需要再由用户去打开。这么做只需要更改手册和添加教程的指引即可。

**Comment by ShiaBox** [comment]
> 对于删除功能来说，我个人更倾向于这个开关设置成常态关闭，有需要再由用户去打开。这么做只需要更改手册和添加教程的指引即可。

理论上来说此功能就是默认关闭的，但是很多用户不理解且不看问号里的说明
在自认为会有正向收益的情况下打开了此开关。

**Comment by Director259** [comment]
> > 对于删除功能来说，我个人更倾向于这个开关设置成常态关闭，有需要再由用户去打开。这么做只需要更改手册和添加教程的指引即可。
> 
> 理论上来说此功能就是默认关闭的，但是很多用户不理解且不看问号里的说明 在自认为会有正向收益的情况下打开了此开关。
> 
> 而且从用法来说，此功能设计之初也仅适用于手表用户，因为其他登录方式在更换设备信息时，都需要重新滑块，只有手表用户才可以更换设备信息自动登录完成规避风控的操作（当然，我不清楚在当前情况下是否还可以如此）。

这个功能对手表也不适用，没有密码的手表协议无法达成自动更新设备信息的能力，就当下的情况仅gocq框架用户而言或许确实可以考虑删去？不知道其他框架的该功能使用情况如何

**Comment by fy0** [comment]
可以考虑移除此选项
