### ISSUE TITLE
请求将滑条更改为允许用户前台手动填入ticket

### ISSUE THREAD

**Issue by ShiaBox** [sealdice/sealdice-core#638]
### 在提问之前...

- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

当前由海豹官方提供的滑条服务基本上百分百会出现237的情况，无法正常使用。
所以实际上只能自行拷贝一份go-cqhttp去服务器后台自行完成登录操作后，关闭go-cqhttp，再由海豹托管，整个流程十分复杂且没有意义。

### 有什么好的想法？

请求将滑条更改为模式2，前端给用户展示官方的滑条网址，允许用户自行使用浏览器调试工具获取ticket，并在前端手动填入ticket提交认证。
用户自行获取ticket也可以规避（有可能存在的）法律风险。

**Comment by kenichiLyon** [comment]
海豹webui本质不是通过嵌套Go-cqhttp程序的界面进行日志记录和操作，相对而言并不是那么容易实现从前端控制Go-cqhttp输入2以及对Go-cqhttp的其他操作。

**Comment by ShiaBox** [comment]
> 海豹webui本质不是通过嵌套Go-cqhttp程序的界面进行日志记录和操作，相对而言并不是那么容易实现从前端控制Go-cqhttp输入2以及对Go-cqhttp的其他操作。

这部分和输入短信验证码的逻辑不一样吗？

**Comment by kenichiLyon** [comment]
> > 海豹webui本质不是通过嵌套Go-cqhttp程序的界面进行日志记录和操作，相对而言并不是那么容易实现从前端控制Go-cqhttp输入2以及对Go-cqhttp的其他操作。
> 
> 这部分和输入短信验证码的逻辑不一样吗？

我还没仔细看源码，但是如果海豹的实现逻辑是一样的话，似乎可以解决相关实现

**Comment by YuSheng133** [comment]
海豹实际上对gocqhttp返回的是模式2，但向用户前端发送的是包含gocqhelper.sealdice.com的自动滑条网址，要改应该不会有特大问题。
`				// 滑条流程
				if slideMode == 1 {
					if strings.Contains(line, "WARNING") && strings.Contains(line, "[WARNING]: 请输入(1 - 2)：") {
						// gocq的tty检测太辣鸡了
						return "2\n"
					}
`

**Comment by fy0** [comment]
和短信验证逻辑差不多，不过需要在ui那块多做一个界面
另外由于过度的风控和膨胀的qsign，考虑在下一个版本中不再推荐内置gocq了……

**Comment by fy0** [comment]
无意义了，迎接新时代吧！

**Comment by Xiangze-Li** [comment]
这个应该是 close as not planned

请 @fy0 留意
