### ISSUE TITLE
[Refactor]: 移除 `MsgContext.GroupRoleLevel`

### ISSUE THREAD

**Issue by Szzrain** [sealdice/sealdice-core#639]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

`MsgContext.GroupRoleLevel` 唯一一次赋值为使其等于 `MsgContext.PrivilegeLevel` 并且其并未暴露给 JS API
因此我认为这个 field duplicate with `MsgContext.PrivilegeLevel`

### 有什么好的想法？

将所有使用了`MsgContext.GroupRoleLevel`的地方替换成`MsgContext.PrivilegeLevel`即可

**Comment by Xiangze-Li** [comment]
原意见有误。赋值后对 PrivilegeLevel 仍有修改，两者并不总是相等。

Ref https://github.com/sealdice/sealdice-core/blob/304e0fe2687be0e20844bfbb017f0b7902773aba/dice/im_session.go#L494

**Comment by fy0** [comment]
我记得这个是用来区分“在群内真实身份”和“群内的权限级别”，大部分时候一样，有些时候不同
