### ISSUE TITLE
[Bug]: .sn expr 不会自动更改名片

### ISSUE THREAD

**Issue by Szzrain** [sealdice/sealdice-core#647]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

使用.sn expr自定义群名片格式时期望自动更改但是并没有

### 如何复现

发送指令
.sn expr CVE-{$tYear}-{$tMonth}{$tDay}{$tHour}
等待时间变化后调用一条其他指令

### 你期望发生的

修改名片的机制应当被自动触发

### 实际上发生的

并没有再次修改我的群名片

### 日志文件

-

### 海豹核心版本

1.4.4

### 操作系统

-

### 帐号类型

-

**Comment by Xiangze-Li** [comment]
原因是模版的更新策略是在「属性」变化时才触发，而不是每个指令执行都触发。例如 st 或 sc 指令执行时。

**Comment by Xiangze-Li** [comment]
请考虑给这个 Issue 更改一个更适配本质的标题, 我一时想不出如何措辞. @Szzrain

**Comment by fy0** [comment]
这些日期的比较难搞。同时时间戳的话极端情况下甚至可以每秒触发一次，这可能对骰主不利……
目前来说插件好像有api可以手动更新，而且通过指令修改时能自动更新，暂时比较够用
