### ISSUE TITLE
[Bug]: st 简化卡破坏原有的 st san-d6

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-core#657]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

期望：`st san-d6` 使理智减少 1d6
实际：被识别为 "san"-"d":6，将角色名改为「理智」并录入了 d = 6

### 如何复现

-

### 你期望发生的

-

### 实际上发生的

-

### 日志文件

-

### 海豹核心版本

SealDice 1.4.5-dev+20240319.6de0346

### 操作系统

-

### 帐号类型

-

**Comment by fy0** [comment]
问题出在：
https://github.com/sealdice/sealdice-core/blob/d4b0e592a897b9d1139f3536c527a91a710cf6d0/dice/ext_exp.go#L515-L531

解决方法1：
如果变量名存在于规则模板上，那么判定为不作为人名 (isName = false)

解决方法2：
在规则模板中加入默认值为0的san等属性

解决方法3：
这几句注释提到的逻辑问题，将其解决
```
						// 注: 这两句逻辑上是对的，但是chVars.Get()第二个值一直返回true，导致永远判定不了是名字
						// _, exists := chVars.Get(name)
						// isName = !exists
```


下版本修复
