### ISSUE TITLE
[Bug]: 群友遇到的问题，llqqnt无法正常解析at相关(cq码模式)

### ISSUE THREAD

**Issue by fy0** [sealdice/sealdice-core#665]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

被识别为消息而不是指令，应该是llob的[CQ:at]格式不同导致的：
![image](https://github.com/sealdice/sealdice-core/assets/1579850/876a8868-8c54-4775-87a1-55714aa38746)

### 如何复现

如图，只要at发指令即可复现

### 你期望发生的

-

### 实际上发生的

-

### 日志文件

-

### 海豹核心版本

1.4.4

### 操作系统

-

### 帐号类型

-

### 附加内容

暂行临时解决方案，修改这个设置，换成消息段：
![I%X85WG~5A_@TVDWEL8Y}_5](https://github.com/sealdice/sealdice-core/assets/1579850/960f6388-41c7-4e8a-a078-b0f1f30fae65)

**Comment by fy0** [comment]
自行搭建测试了一下，发现是正常的，奇怪
![image](https://github.com/sealdice/sealdice-core/assets/1579850/db2e612c-94a3-4c8b-89a7-9613980db2d8)

**Comment by fy0** [comment]
原来是旧版本 llob，三周前的版本，后来修改掉删除了：
https://github.com/LLOneBot/LLOneBot/commit/4249f4e088e09493b688c83b1e7f789854fd57e6

**Comment by fy0** [comment]
re = regexp.MustCompile(`\[CQ:at(?:,mention=.+?)?,qq=(\d+?)]`)

**Comment by Xiangze-Li** [comment]
> 原来是旧版本 llob，三周前的版本，后来修改掉删除了： [LLOneBot/LLOneBot@4249f4e](https://github.com/LLOneBot/LLOneBot/commit/4249f4e088e09493b688c83b1e7f789854fd57e6)

如果是这种情况，不建议为了特定几个版本的上游bug修改我们的逻辑。收益不大还可能引入问题。

**Comment by Xiangze-Li** [comment]
建议不处理此 Issue。
