### ISSUE TITLE
[Bug]: llqqnt的入群宣言，以及入群检测可能存在问题

### ISSUE THREAD

**Issue by fy0** [sealdice/sealdice-core#666]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

据说不会发送入群宣言，同时如果之前有在群内，而且处于关闭状态，再次进群仍会处于关闭

### 如何复现

-

### 你期望发生的

-

### 实际上发生的

-

### 日志文件

-

### 海豹核心版本

1.4.4

### 操作系统

-

### 帐号类型

qq

**Comment by fy0** [comment]
经测试，目前版本的llob不会发送入群事件（3.19.3），即入群后海豹无法得知其进群

**Comment by Xiangze-Li** [comment]
上游问题不由海豹解决
