### ISSUE TITLE
希望可以在发送风控邮件时添加“本来要发送的信息”

### ISSUE THREAD

**Issue by baiyu-yu** [sealdice/sealdice-core#669]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

每天都可以收到数封风控邮件，但是无法确定是用户进行了非好友暗骰还是本身自定义回复或者插件等设置有误无法发出还是真正风控

### 有什么好的想法？

希望可以在发送风控邮件时加上“本来要发送的信息”，如果可以希望也可以加上触发该风控的指令

**Comment by Xiangze-Li** [comment]
很不幸地，从目前的逻辑来看，发送提醒邮件时并不知道没发出去的是哪一条消息。因此也没办法加在邮件里。

参见：[源代码](https://github.com/sealdice/sealdice-core/blob/f6985a7aa09ef792ef9732959b7c95ae67cc31d9/dice/platform_adapter_gocq.go#L953)

@fy0 需要木落确认一下这里逻辑是否确实做不到，然后看看关掉

**Comment by fy0** [comment]
gocq返回的风控通知里，没有被风控的消息id，因此无法进行这个操作
