### ISSUE TITLE
适配 logget <日志名> 以及 log get<日志名> 命令的想法

### ISSUE THREAD

**Issue by kenichiLyon** [sealdice/sealdice-core#674]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

部分用户会忘记海豹的 log get <日志名> 指令中带有空格，而会使用logget <日志名> 以及 log get<日志名>。故希望海豹可以适配这一指令，等价于 log get <日志名>。

original idea by 仓鼠（QQ:3340199667）& Director 259

**Comment by Director259** [comment]
logget 日志名这个指令是适配的，不适配会给出指令提示的是log get日志名，即get和日志名中间没有空格的指令，这里这个空格不知道是不是存在指令识别的考虑大概得等开发组看看
