### ISSUE TITLE
[Bug]: 被禁用的指令会在其他人被at时响应

### ISSUE THREAD

**Issue by kenichiLyon** [sealdice/sealdice-core#675]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

如图，本不应该响应的艾特指令被响应了，也并没有显示代骰，排除代骰出错的可能。
![9C72F03145BB1CFE4D3DFC121D32889F](https://github.com/sealdice/sealdice-core/assets/128369797/ae1a3445-bd59-402c-8fa3-fce3efd9e3a2)

### 如何复现

接入拉格兰（版本为3.23的action中 Largrange.OneBot release）
正向websocket接入海豹，海豹版本为1.4.4
禁用gugu拓展
艾特别骰发送指令

### 你期望发生的

本应该是显示代骰或忽略此指令

### 实际上发生的

本不应该响应的艾特指令被响应了

### 日志文件

![QQ截图20240325224952](https://github.com/sealdice/sealdice-core/assets/128369797/bd28bbb8-9adb-4aff-b932-3c75b07f8d03)

### 截图

![QQ截图20240325224952](https://github.com/sealdice/sealdice-core/assets/128369797/547a0178-b0df-49eb-b059-a433dd7fdeb5)
![9C72F03145BB1CFE4D3DFC121D32889F](https://github.com/sealdice/sealdice-core/assets/128369797/904a1fcf-234f-4fad-94c3-605e0b566889)

### 海豹核心版本

1.4.4 v20240310

### 操作系统

Windows Server 2022

### 帐号类型

QQ

**Comment by Director259** [comment]
应该是禁用指令的问题，我的海豹在12x版本就复现过，具体版本号记不清了，当时只在q群反馈后来忘记上issue了，翻出来的当时的截图时间是2023-3-21
![OU7EP9AOO$C)K2F90H`2BR3_tmb](https://github.com/sealdice/sealdice-core/assets/127825341/86a8da0e-602b-4dd8-9df6-d97abf4da921)
![GHV7}S%XK_(6%P7(S_ BG9T_tmb](https://github.com/sealdice/sealdice-core/assets/127825341/57249d5b-3d3a-41e5-923c-69013fdc1c4c)
![NE0B8`6{C)K0CB}$(8XUU6O_tmb](https://github.com/sealdice/sealdice-core/assets/127825341/012798b7-084a-4aa1-8e95-b2db9b05676d)

**Comment by Director259** [comment]
![GHV7}S%XK_(6%P7(S_ BG9T_tmb](https://github.com/sealdice/sealdice-core/assets/127825341/446d46a3-c1f1-4158-bf75-298ab8119d59)
图怎么落了我补一下
