### ISSUE TITLE
[Bug]: 通过染色器下载的 doc Log 内容重复

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-core#679]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

*转述*

通过染色器下载的 doc 格式 Log 文件，在 Log 结束的位置（`log end`）后多次重复出现了之前的内容。

本地日志 和 染色器的编辑窗口 均是正常，在下载 word 文件后出现文本重复。

### 如何复现

偶现，但并非个例

### 你期望发生的

/

### 实际上发生的

/

### 日志文件

/

### 海豹核心版本

/

### 操作系统

/

### 帐号类型

/

### 附加内容

[皇冠战争1-1  流言怎么会影响本体呢你们说是吧.zip](https://github.com/sealdice/sealdice-core/files/14767016/1-1.zip)

[另一份出现此问题的染色器链接](http://log.weizaima.com/?key=3x5w#459339)

**Comment by fy0** [comment]
https://github.com/sealdice/story-painter/commit/1f3ff8e7e5f2480bcf5ec6e93c2e589ce7614e38 已经修复
