### ISSUE TITLE
[功能] 黑名单 API 开放更多控制

### ISSUE THREAD

**Issue by oissevalt** [sealdice/sealdice-core#681]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

当前面对插件开放的黑名单 API 仅支持插入单条记录（单个原因+地点，且时间戳无法控制）。在与云端黑名单对接时，不方便从远端拉取包含多个原因/时间/地点的黑名单记录。

### 有什么好的想法？

希望添加相关 API，通过插件端构建的 BanListItemInfo 来覆盖或累积更新本地记录。

**Comment by Xiangze-Li** [comment]
当前接口已经足以使用
