### ISSUE TITLE
[Bug]: 145-dev 内置拉格兰问题收集

### ISSUE THREAD

**Issue by fy0** [sealdice/sealdice-core#692]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

Win64:
* ~~无法在路径中含有空格的情况下启动~~

共有:
* ~~登录状态过程中，一直显示“重新登录”“禁用”~~
* ~~“重新登录”按钮不可用（可考虑移除此按钮）~~
* ~~登录后，禁用，再启用，界面会卡在帐号登录~~
* （插播消息）拉格兰似乎不能设置Host为0.0.0.0，会报错

### 如何复现

-

### 你期望发生的

-

### 实际上发生的

-

### 日志文件

-

### 海豹核心版本

1.4.5-dev

### 操作系统

-

### 帐号类型

-

**Comment by MX-fox** [comment]
![Screenshot_20240402_231816_com sealdice dice](https://github.com/sealdice/sealdice-core/assets/106176511/b0b403d4-1b8c-4827-804b-8a9dc24c35f5)
lagrange进程异常退出：exit status 134
疑似因为网络异常（如校园网），可通过切换网络解决

**Comment by fy0** [comment]
概率出现：

![image](https://github.com/sealdice/sealdice-core/assets/1579850/abc13d99-ad0e-4bd4-9c95-f831111eb802)

同时无法连接，配置文件被生成为：

![K$S2 AGA@ J4_L@X2A3OJJ3](https://github.com/sealdice/sealdice-core/assets/1579850/4aa91c2a-f9a2-4beb-a6b3-240c5169f28c)

![{IL3EBZM7C%@MSBU6@%Q)NL](https://github.com/sealdice/sealdice-core/assets/1579850/ccaf9118-2f4f-46ee-a06e-6e0e9fc4ad38)

**Comment by MX-fox** [comment]
![K2{S@TE0@`)FO~V76YF MWI](https://github.com/sealdice/sealdice-core/assets/106176511/3b62988c-e256-4111-9f51-c5f0ef2c3b6c)
如果文件路径带空格，会找不到lagrange程序

**Comment by MX-fox** [comment]
![image](https://github.com/sealdice/sealdice-core/assets/106176511/c725e41f-1d14-47ae-a097-12c7fc90ab38)
如果添加账号时，海豹文件夹内已有该账号的配置文件，会不进行ws连接

**Comment by MX-fox** [comment]
出现海豹与lagrange短时间内突然两次断开连接，第二次断开不进行重新连接
<img width="934" alt="image" src="https://github.com/sealdice/sealdice-core/assets/106176511/d716c0eb-d965-482d-932e-e2c3c26ff427">
可确认lagrange没有崩溃，断开时间内有收到群消息
<img width="1019" alt="image" src="https://github.com/sealdice/sealdice-core/assets/106176511/58dcde3e-d63f-4fb9-9f5c-82c286b02ce4">
需要骰主手动重新登录
<img width="1042" alt="image" src="https://github.com/sealdice/sealdice-core/assets/106176511/d193ca8d-e632-4d07-af9d-7ebbc73320dd">

**Comment by Xiangze-Li** [comment]
再有问题可以单开issue处理，堆积一处无益于查找和管理
