### ISSUE TITLE
[Bug]: master指令群聊中的错误响应问题

### ISSUE THREAD

**Issue by PaienNate** [sealdice/sealdice-core#696]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

如题，在群中@某位成员并使用.master add时，其他骰子均进行了响应。
![Image_1712327847051](https://github.com/sealdice/sealdice-core/assets/68044286/9a790f0a-d60e-41c3-8c29-4fc5b2d9e188)

### 如何复现

@一只骰子，并使用.master相关指令

### 你期望发生的

仅有被@的骰子响应指令

### 实际上发生的

群里变成了大型牛头人现场

### 日志文件

无需

### 截图

![Uploading Image_1712327847051.png…]()

### 海豹核心版本

1.4.5-dev+20240405.a7194b9 arm64

### 操作系统

唔，似乎是在测试的手机豹捏。

### 帐号类型

QQ

### 使用协议

PC

### 附加内容

没了

**Comment by Szzrain** [comment]
master add 本身就支持@，这应该是预期内的行为
