### ISSUE TITLE
响应黑名单的退群指令

### ISSUE THREAD

**Issue by MX-fox** [sealdice/sealdice-core#699]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

当前骰娘无法响应响应黑名单的退群指令

### 有什么好的想法？

响应黑名单的退群指令

**Comment by Xiangze-Li** [comment]
为什么需要响应黑名单用户的退群指令？

**Comment by Xiangze-Li** [comment]
不能确认需求真实存在
