### ISSUE TITLE
[Bug]: Windows 平台正常退出依然会生成崩溃日志

### ISSUE THREAD

**Issue by Szzrain** [sealdice/sealdice-core#708]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

正常方式退出程序（点击托盘菜单中的“退出程序”）依然会生成崩溃报告

### 如何复现

1. 启动海豹
2. 等待几分钟
3. 右键右下角退出程序
4. 复现

### 你期望发生的

不生成崩溃报告

### 实际上发生的

生成了崩溃报告

### 日志文件

```
2024-04-09T17:39:14.901-0400    info    dice/platform_adapter_kook.go:352       KOOK 连接成功，账号<SzzRain的测试机器人>(KOOK:2210765268)       {"dice": "default"}
2024-04-09T17:39:14.903-0400    info    dice/config.go:2388     保存数据        {"dice": "default"}
2024-04-09T20:23:32.359-0400    info    sealdice-core/main.go:44        程序即将退出，进行清理……
2024-04-09T20:23:32.388-0400    info    sealdice-core/main.go:44        程序即将退出，进行清理……
panic: close of closed channel [recovered]
        panic: close of closed channel

goroutine 1 [running, locked to thread]:
sealdice-core/dice.CrashLog()
        C:/Users/MSI-NB/GolandProjects/sealdice-core/dice/dice.go:756 +0x174
panic({0x7ff667ddd000, 0x7ff6686bb430})
        C:/Users/MSI-NB/go/go1.20.2/src/runtime/panic.go:890 +0x263
github.com/blevesearch/bleve/v2/index/scorch.(*Scorch).Close(0xc0020f7b00)
        C:/Users/MSI-NB/go/pkg/mod/github.com/blevesearch/bleve/v2@v2.3.10/index/scorch/scorch.go:332 +0xa5
github.com/blevesearch/bleve/v2.(*indexImpl).Close(0xc001fc4070)
        C:/Users/MSI-NB/go/pkg/mod/github.com/blevesearch/bleve/v2@v2.3.10/index_impl.go:852 +0xa2
sealdice-core/dice.(*HelpManager).Close(0xc0018f8180)
        C:/Users/MSI-NB/GolandProjects/sealdice-core/dice/dice_help.go:161 +0x36
main.cleanUpCreate.func1()
        C:/Users/MSI-NB/GolandProjects/sealdice-core/main.go:112 +0x310
main.main()
        C:/Users/MSI-NB/GolandProjects/sealdice-core/main.go:429 +0x1517

Process finished with the exit code 2
```

### 海豹核心版本

https://github.com/sealdice/sealdice-core/commit/85a79999351f4de8e58b6a12b15cf1e5143f5674

### 操作系统

Windows

### 帐号类型

Kook（按理说无关）

**Comment by Fripine** [comment]
V1.4.4版本，纯净骰，QQ分离部署，测试了5分钟、10分钟、20分钟时退出程序，无法复现，需要更详细的复现流程或配置说明

**Comment by Szzrain** [comment]
> V1.4.4版本，纯净骰，KOOK连接，测试了5分钟、10分钟、20分钟时退出程序，暂时无法复现，需要更详细的复现流程或配置说明

偶现 bug，我试了下也无法稳定复现

**Comment by Fripine** [comment]
已找到复现流程：启动sealdice-core.exe后，在右下角提示“sealdice藏在托盘区域了”的同时右键托盘图标点击“退出”
![image](https://github.com/sealdice/sealdice-core/assets/84258717/bd53d269-4d58-4cf6-b9c0-4ed31bd9bcfc)

崩溃日志一律指向 dice_help.go:161

> https://github.com/sealdice/sealdice-core/blob/ca1629ae52bd7fc9a9275c356469f496ab23d42c/dice/dice_help.go#L158-L167

**Comment by MintCider** [comment]
直接原因：

https://github.com/sealdice/sealdice-core/blob/a6c2c5afefa8715313a6890b5226d55ac73d845d/dice/dice_help.go#L158-L167

这个函数被两个协程快速调用两次，在检查 `m.Index` 是否为空指针时发生数据竞争，导致 `m.Index.Close()` 被重复调用。

调用是由这个清理函数发起的：

https://github.com/sealdice/sealdice-core/blob/a6c2c5afefa8715313a6890b5226d55ac73d845d/main.go#L44

两次重复调用分别由主函数中的 defer 和托盘退出回调触发：

https://github.com/sealdice/sealdice-core/blob/a6c2c5afefa8715313a6890b5226d55ac73d845d/main.go#L398

https://github.com/sealdice/sealdice-core/blob/a6c2c5afefa8715313a6890b5226d55ac73d845d/tray_windows.go#L143-L148

虽然托盘退出回调执行了 `os.exit(0)`，但是在此之前已经执行了 `systray.Quit()`，而根据 `systray.Run()` 的描述：

> `func systray.Run(onReady func(), onExit func())`
> Run initializes GUI and starts the event loop, then invokes the onReady callback. It blocks until systray.Quit() is called.

当`systray.Quit()` 被调用后，主函数失去阻塞，触发了 defer 的执行。

**Comment by fy0** [comment]
#803 进行了对应的修复，这里进行了对cleanup函数的原子锁保护
