### ISSUE TITLE
使用seal.ext.getTemplateConfig获取配置项的时候报错

### ISSUE THREAD

**Issue by x00912342** [sealdice/sealdice-core#715]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [x] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

使用seal.ext.registerTemplateConfig注册配置项之后再使用seal.ext.getTemplateConfig会报错

### 如何复现

1.注册扩展
2.使用seal.ext.registerTemplateConfig注册配置项
3.使用seal.ext.getTemplateConfig赋值

### 你期望发生的

能正常获取到设置的配置项

### 实际上发生的

日志报错

### 日志文件

![L @PJZ(P%S_A6Q2WM}TP9R9](https://github.com/sealdice/sealdice-core/assets/140057940/4da87ccd-ff32-4b7b-94c4-87c0e3b8f758)

### 截图

![KR8URXA0L}{MTPITJ~XE4OB](https://github.com/sealdice/sealdice-core/assets/140057940/89721484-04a6-4edb-9979-10a5b992a41e)

### 海豹核心版本

1.4.5

### 操作系统

Windows

### 帐号类型

QQ

**Comment by Fripine** [comment]
无法从[]interface{}断言[]string

**Comment by x00912342** [comment]
> 无法从[]interface{}断言[]string，上个版本是否有这个问题

我之前是1.4.4，然后升级到1.4.5均有这个报错

**Comment by Fripine** [comment]
> > 无法从[]interface{}断言[]string，上个版本是否有这个问题
> 
> 我之前是1.4.4，然后升级到1.4.5均有这个报错

已了解，正在尝试修复

**Comment by x00912342** [comment]
> > > 无法从[]interface{}断言[]string，上个版本是否有这个问题
> > 
> > 
> > 我之前是1.4.4，然后升级到1.4.5均有这个报错
> 
> 已了解，正在尝试修复

好的，辛苦了
