### ISSUE TITLE
[Bug]: master指令在有@前缀时依然触发

### ISSUE THREAD

**Issue by MX-fox** [sealdice/sealdice-core#716]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

master指令在有@前缀时依然触发
![Screenshot_2024-04-11-22-17-17-10_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/sealdice/sealdice-core/assets/106176511/658337a1-09c8-4861-81f5-97096e0f148d)

### 如何复现

当多个骰娘同时开启时，@其中一位骰娘使用。master add me

### 你期望发生的

只有被@的骰娘回应

### 实际上发生的

开起的骰娘都会回应，且会将被@的骰娘加入骰主列表

### 日志文件

![Screenshot_2024-04-11-22-17-17-10_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/sealdice/sealdice-core/assets/106176511/3afe41b3-b0cb-4632-8331-6dfe0efeebe0)

### 海豹核心版本

1.4.5

### 操作系统

Windows

### 帐号类型

QQ

**Comment by Szzrain** [comment]
dupe
