### ISSUE TITLE
优化：删除查询时标题不必要的斜杠（/）

### ISSUE THREAD

**Issue by nodisease** [sealdice/sealdice-core#720]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

如图，以**xlsx格式**录入的帮助文档，如果该条目**没有设置同义词**，那么在查询时标题会在末尾多出一个不必要的斜杠。
![1](https://github.com/sealdice/sealdice-core/assets/102459355/f1045982-6f0f-4d1c-a025-a1e06d8cc86a)

### 有什么好的想法？

删去这个斜杠。

**Comment by Fripine** [comment]
已找到问题所在，尝试修正
