### ISSUE TITLE
[Behavior Check] 删除角色卡(pc rm)指令在角色卡与当前角色同名时的行为确认

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-core#735]
## 当前行为

由于同名, 即使当前角色并非是绑定的卡 (绑定的卡无法删除), 也会触发逻辑清除当前角色的数据和昵称.

如下:

```
$ /st show
<饭岛薰>的个人属性为:
力量:50 敏捷:50 体质:60 体型:50 ...

$ /pc save
<饭岛薰>的角色列表为:
 1 [×] 饭岛薰 #coc7
[√]已绑 [×]未绑 [★]其他群绑定

$ /pc rm 饭岛薰
角色"饭岛薰"删除成功
由于你删除的角色是当前角色，昵称和属性将被一同清空

$ /st show
<User>的个人属性为:
未发现属性记录。
```

## 问题点

既然已经禁止了删除绑定卡, 能够删除的就一定是非绑定卡 (如通过 pc load 以非绑定模式加载数据得来, 或单纯是同名). 这种情况下, 删除存储中的角色卡并不一定代表当前角色数据也需要清除. 需要确认行为.

## 可能的替代行为

无论当前角色名, 在 `pc rm` 执行中都不操作当前角色.

**Comment by Xiangze-Li** [comment]
@fy0 @Szzrain @JustAnotherID @oissevalt

**Comment by Fripine** [comment]
#51

**Comment by Xiangze-Li** [comment]
> #51

并非 51 所列问题，但是，如果采用了提出的替代行为，有望使 51 的前提消失

**Comment by fy0** [comment]
等待复活dev分支，这个指令已经被重写了
