### ISSUE TITLE
[Bug]: 插件的 buntdb 在 shrink 时发生无权访问文件问题导致 panic

### ISSUE THREAD

**Issue by PaienNate** [sealdice/sealdice-core#749]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

![b2a0eb078f5fda50323408e6f9e633f1](https://github.com/sealdice/sealdice-core/assets/68044286/386bad78-9b1a-4d0c-8137-c766d467d183)
如图所示。

### 如何复现

暂不明确，已知用户使用数个插件。

### 你期望发生的

海豹正常活着

### 实际上发生的

海豹突然去世

### 日志文件

（时间太久远了日志已经没有，十分抱歉，但日志中没有任何报错信息）

### 截图

-

### 海豹核心版本

1.4.5

### 操作系统

Windows

### 帐号类型

QQ KOOK DODO

### 使用协议

拉格兰

### 附加内容

-

**Comment by Xiangze-Li** [comment]
Hopefully fixed...

**Comment by PaienNate** [comment]
> Hopefully fixed...

（合十）
