### ISSUE TITLE
[Bug]: 不确定条件下，电脑端在已登陆过的账号重新试图登陆时无法登陆并大量报错

### ISSUE THREAD

**Issue by Polaris007920** [sealdice/sealdice-core#751]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

不确定条件下，电脑端在已登陆过的账号重新试图登陆时，无法登陆并大量报错，bug后账号通过web-ui无法正常重新登陆，webui内删除账号后登陆也无法登陆
相关日志文件已在后续内展示，并已删除可能的具体账号敏感信息，且作具体操作的注释
在删除根目录-default-extra下账号信息后，重新扫二维码登陆有效，bug虽然可能没有解决，但海豹可用了

### 如何复现

不明

### 你期望发生的

海豹活着

### 实际上发生的

好像出了点小问题

### 日志文件

[bug-view.txt](https://github.com/sealdice/sealdice-core/files/15126417/bug-view.txt)

### 海豹核心版本

1.4.5

### 操作系统

Windows

### 帐号类型

QQ

### 使用协议

lagrange

**Comment by Polaris007920** [comment]
补充：接入方式为1.4.5后采取的“内置客户端”

**Comment by Fripine** [comment]
问一下

> // 因发现在手机端QQ内显示“linux已登陆”，尝试在群聊内回复关键词检测是否能正常回复，发现仍异常

该事件发生时，骰子后台界面 - 账号设置 内，该账号状态是什么？是否为“已连接”？

**Comment by Polaris007920** [comment]
> 问一下
> 
> > // 因发现在手机端QQ内显示“linux已登陆”，尝试在群聊内回复关键词检测是否能正常回复，发现仍异常
> 
> 该事件发生时，骰子后台界面 - 账号设置 内，该账号状态是什么？是否为“已连接”？

因为有些久远不太记得了，但应该是“断开”

**Comment by Polaris007920** [comment]
在本issue内再报告一个bug，禁止登录，看lagrange那边类似情况说要配签名服务器，但内置客户端之前可行不知道为什么现在又不行了。
是账号无法发送信息后重新尝试登录，显示：

2024-05-11T12:40:04.589+0800    warn    dice/platform_adapter_lagrange_helper.go:155    onebot | fail: Lagrange.Core.BotContext[0]
        {"dice": "default"}
2024-05-11T12:40:04.590+0800    warn    dice/platform_adapter_lagrange_helper.go:155    onebot |       [2024-05-11 12:40:04] [WtExchangeLogic] [FATAL]: Tag: 禁止登录
        {"dice": "default"}
2024-05-11T12:40:04.590+0800    error   dice/platform_adapter_lagrange_helper.go:158    onebot |       [2024-05-11 12:40:04] [WtExchangeLogic] [FATAL]: Tag: 禁止登录
        {"dice": "default"}
2024-05-11T12:40:04.590+0800    warn    dice/platform_adapter_lagrange_helper.go:155    onebot | State: 登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。

目前账户已无法重新登陆，也有可能是风控原因，但确实在反馈群和github页面都没见过相关issue

**Comment by Fripine** [comment]
骰子已登录但无法回应指令的原因是SignServer没连上，这边有个逻辑上的错误是，内置lagr方式接入的账号，应当在其登录成功后再调用ServeQQ尝试进行WS正向连接

**Comment by Fripine** [comment]
#830

**Comment by Fripine** [comment]
#831

**Comment by Fripine** [comment]
已定位到具体原因，上游问题

**Comment by Fripine** [comment]
已提交上游修复，拉最新build进行测试https://github.com/LagrangeDev/Lagrange.Core/actions/runs/9758430965

**Comment by JustAnotherID** [comment]
Beta 版本已修复
