### ISSUE TITLE
[功能] 向插件提供定时任务机制

### ISSUE THREAD

**Issue by JustAnotherID** [sealdice/sealdice-core#761]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前如果需要在插件实现定时触发功能，需要自行维护，没有一个简便的 API 支持相关功能。

### 有什么好的想法？

希望提供一个定时任务机制，支持按 cron 设置触发时间。同时对最常用的「每天固定时间触发」提供单独支持。
拟定的 API 如下：
```javascript
seal.ext.registerTask(ext, 'cron', '30 8 * * *', (taskCtx) => {});
seal.ext.registerTask(ext, 'daily', '8:00', (taskCtx) => {}); // 24 小时制
```

**Comment by Xiangze-Li** [comment]
需要细化. 目前想到的问题可能包括:

1. 如何删除添加的任务?
   可能: 添加任务接口返回任务的 ID, 提供根据 ID 删除任务的接口.
2. 是否能够支持持久化? 
   如果支持, 能否做到重启前后 ID 不变?
3. 在添加的任务函数里能使用哪些对象?

**Comment by MintCider** [comment]
滋瓷！

**Comment by MintCider** [comment]
> 2\. 是否能够支持持久化

Go 不支持持久化一个 callable 吧？有什么 workaround 么？

**Comment by Xiangze-Li** [comment]
> > 2. 是否能够支持持久化
> 
> Go 不支持持久化一个 callable 吧？有什么 workaround 么？

所以我才让ID来补充描述……

他的详细设计不需要持久化 callable。插件不能动态地使用这里的定时器，而是只从这里获取打点。以定时任务举例，插件可能只注册一个 `* * * * *` 的定时器，并在每次打点时轮询任务。

**Comment by JustAnotherID** [comment]
是的，我之前设想的只是提供一个获取打点的机制。

1. core 中有个公共的 cron 用于提供计时。
2. 每个插件可以通过参数获取不同频率的打点，至于获取打点后的逻辑如何处理都交给插件自行处理。
