### ISSUE TITLE
[License] 涉及 LagrangeGo 的项目许可证问题

### ISSUE THREAD

**Issue by JustAnotherID** [sealdice/sealdice-core#773]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

新引入的 [LagrangeGo](https://github.com/LagrangeDev/LagrangeGo) 使用 AGPLv3 协议开源，具有传染性。作为开源社区的一部分，我们应当尊重相关协议的限制。

### 有什么好的想法？

两个可能选择：
1. 不更改当前协议，移除或隔离主线代码中的 LagrangeGo 的引用。
2. 直接切换到 AGPLv3。

个人倾向于选择 2，更换协议对我们来说并没有什么实质影响。

@fy0 @Szzrain @Xiangze-Li @oissevalt @FlameTEXT @Fripine @PaienNate @yichere

**Comment by JustAnotherID** [comment]
根据 #774 中的意见，方案为先移除对 LagrangeGo 的直接引用（悲

**Comment by Xiangze-Li** [comment]
尊重 BDFL 的意见，同时希望 BDFL 意识到自己做出的决定对整个开发组的影响。

**Comment by JustAnotherID** [comment]
不舍得 Szzrain 佬当前的贡献变成无用功，进行了一个分叉保留：
https://github.com/sealdice/libre-sealdice-core

**Comment by Szzrain** [comment]
#779
