### ISSUE TITLE
.find 指令的结果翻页功能

### ISSUE THREAD

**Issue by Szzrain** [sealdice/sealdice-core#79]
.find xxx
.find xxx +
.finx xxx -

**Comment by FlameTEXT** [comment]
翻不翻页意义不大，因为结果限制到最多10项，一条消息就能显示完。

**Comment by SunnyJoyce** [comment]
> 翻不翻页意义不大，因为结果限制到最多10项，一条消息就能显示完。

这个诉求的体现是在于现版本海豹将搜索结果限制相关结果仅显示到4条，其余更多相关结果则默认不显示，如需显示需要打出.find <关键字> --num=10，指令相对繁琐。这会导致一些搜索相关量大的词汇反而找不到用户需求的那个词条。例：在dnd5e一类数据库大的帮助文档中，如想搜索法术列表如一环法师列表，会导致结果显示不全。

**Comment by Xiangze-Li** [comment]
按照“指定页码”的逻辑实现，而不是“翻页”
