### ISSUE TITLE
[JsAPI请求] 支持修改玩家名字

### ISSUE THREAD

**Issue by kagangtuya-star** [sealdice/sealdice-core#794]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前玩家的属性与名字，只能通过nn与st指令修改。

### 有什么好的想法？

提供一系列的api接口
- 获取给定ctx.player的属性的对应值；
- 修改给定ctx.player的属性为新值；
- 修改给定ctx.player的名字

可以实现一些对于房规的细化支持，和重命名代骰等

**Comment by Xiangze-Li** [comment]
关于你所说第一点和第二点:

```js
seal.vars.intGet(ctx, '侦查')
seal.vars.intSet(ctx, '侦查', 70)
```

**Comment by Szzrain** [comment]
``` go
type GroupPlayerInfoBase struct {
	Name                string        `yaml:"name" jsbind:"name"` // 玩家昵称
// ...
}
```

**Comment by Xiangze-Li** [comment]
> ```go
> type GroupPlayerInfoBase struct {
> 	Name                string        `yaml:"name" jsbind:"name"` // 玩家昵称
> // ...
> }
> ```

这玩意可以直接改啊？
