### ISSUE TITLE
[功能]：私骰模式实现的一种思路

### ISSUE THREAD

**Issue by kenichiLyon** [sealdice/sealdice-core#796]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

同 #791 
对该issue做一个细化

### 有什么好的想法？

1、与白名单联动，可以尝试在私骰模式，由master通过 **.ban trust** 指令给予trust用户，无trust用户的好友申请自动忽略/拒绝，同时，检测到无trust用户强制拉群，自动退出该群并发送相关信息（类似黑名单操作）
2、如果上述方案存在实现困难，则是否可以存在中间件可以实现通过调用海豹的黑白名单进行退群和好友申请相关处理？

**Comment by JustAnotherID** [comment]
直接评论在 #791 下吧，同一个需求不要提两个 issue。
