### ISSUE TITLE
海豹1.4.6自定义移动键的变更建议

### ISSUE THREAD

**Issue by chayemiao** [sealdice/sealdice-core#809]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

使用手机浏览器（Safari、夸克），在打开1.4.6dev版的webui进行对于自定义回复的编辑时，发现移动键删除了，这让调整每项自定义回复的前后顺序变得麻烦了。
尝试长按拖拽，但手机本身小屏幕，长按后经常选中字体。

### 有什么好的想法？

1.4.6dev把侧边栏隐藏了，其实已经减少了原本1.4.5由于侧边栏占位过大导致常常误触到移动键的问题，1.4.6移动键其实可以不变更。
或者是否可以设置一个开关？打开后移动键显示，关闭后移动键隐藏

**Comment by JustAnotherID** [comment]
自定义回复的移动键消失是 Bug，已修复。
