### ISSUE TITLE
关于find指令在helpdoc内文件过多时，查询功能略有些繁琐的问题

### ISSUE THREAD

**Issue by bigmiin** [sealdice/sealdice-core#832]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

用户反馈在使用find时不能直接得出一个结果，而是需用再使用一次指令查询具体时体感有些繁琐，具体表现如图
![AD3BBE8EA01C3CD1F5DAFD36A325BB68](https://github.com/sealdice/sealdice-core/assets/160385557/2cb0c673-964c-4bd7-8c4e-21a742f7a848)
![B1F6B71DCAA3DE25D275CF93FBE7C6F7](https://github.com/sealdice/sealdice-core/assets/160385557/57307cb1-6ef2-4b64-a18a-bd006f52abe1)

### 有什么好的想法？

能否在查询时显示匹配度最高的结果，想实现的效果具体为
![72A3D510D14E35C469A16539F0BCB4BF](https://github.com/sealdice/sealdice-core/assets/160385557/e28f7b51-4c88-4611-8f0b-e90812d5e6d3)

**Comment by JustAnotherID** [comment]
find 在只有一条结果时本身就会默认输出查询结果。
这里不输出查询结果的原因是因为装载了多种规则，其中存在多条极其相似的项，这种情况下是无法猜想出具体需要哪条记录的。
请使用 `.find #分组` 来尝试缩小搜索分组，支持设置默认分组，参见 [手册-核心指令](https://docs.sealdice.com/use/core.html#find-%E8%AF%8D%E6%9D%A1%E6%9F%A5%E8%AF%A2%E6%8C%87%E4%BB%A4)。
