### ISSUE TITLE
[150 Bug](DnD): 与生命值上限和下限相关的功能缺失

### ISSUE THREAD

**Issue by Szzrain** [sealdice/sealdice-core#854]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在 #821 中 删掉了对于 DND:受到伤害_超过HP上限_附加语  DND:受到伤害_昏迷中_附加语 和 DND:受到伤害_进入昏迷_附加语 的处理

### 有什么好的想法？

将相关功能重新实现

**Comment by Xiangze-Li** [comment]
对应的是 DnD 的生命值特殊规则完全缺失，就我目前已知的列出如下：

1. hp 在将要减到负数时：如果溢出的伤害小于生命值上限，则本次应只减到 0，并提示昏迷；如果溢出伤害大于等于生命值上限，立即死亡
2. hp 增加时不能超过上限
3. 在 hp 为零（昏迷）时再受到伤害，直接记一次死亡豁免失败

**Comment by Szzrain** [comment]
同时希望增加的额外功能：buff hpmax 时，增长 hp 的上限变为 buff_hpmax + hpmax
