### ISSUE TITLE
[Bug] (DND): 测试版问题汇总

### ISSUE THREAD

**Issue by Szzrain** [sealdice/sealdice-core#855]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

- [x] 1. 使用 .set dnd 时不会正确设置骰子面数
- [x] 2. 属性检定时有时候出现不正确的调整值
- [ ] 3. dnd 模式下 .st show 显示无属性记录
- [x] 4. 无法录入技能附加修正和熟练
- [x] 5. 技能调整值没有被正确计算

### 使用 .set dnd 时不会正确设置骰子面数

1. 输入.set dnd
2. 输入.r
3. 问题产生

### 属性检定时有时候出现不正确的调整值

1. 输入 .st 智力*=20 
2. 输入 .rc 智力
3. 问题产生

### dnd 模式下 .st show 显示无属性记录

1. 在上面的基础上，输入 .st show
2. 问题产生

### 无法录入技能附加值和熟练，调整值无法正确计算

1. 在上面的基础上，输入 .st 奥秘*=1
2. 输入 .rc 奥秘
3. 问题产生

### 你期望发生的

- [x] 1. 使用.set dnd 时骰子面数被设置为 20
- [x] 2. 属性检定时正确计算调整值 （在下面的演示案例中正确的调整值应为 +5）
- [ ] 3. .st show 展示正确的内容
- [x] 4. 能够正确录入技能附加值和熟练
- [x] 5. 正确计算技能调整值

### 使用 .set dnd 时不会正确设置骰子面数

骰子提示已切换骰子面数，实际上没有，还是原来的骰子面数

### 属性检定时有时候出现不正确的调整值

在上面的演示案例中按照步骤复现后的骰子输出：

```
<DM>的“智力”检定(dnd5e)结果为:
15[D20=15] + -5[智力调整值-5] = 10
```

### 日志文件

-

### 海豹核心版本

https://github.com/sealdice/sealdice-build/commit/fa36ced00b64ca5fa309790825f599f93becf6e7

### 操作系统

-

### 帐号类型

QQ

**Comment by Xiangze-Li** [comment]
使用 `st 智力=X` 录入后直接查数据库，发现并无有任何数据落盘

![image](https://github.com/sealdice/sealdice-core/assets/45380560/65e6bcf0-277d-4038-8ed8-e952aa2d3a5f)

**Comment by Szzrain** [comment]
补充：在按照步骤复现后 `.st show 智力 ` 的输出如下
```
干员<DM>拥有以下属性，希望这能够帮助你在这片大地上生存下来。
智力*:0
```

因此我合理怀疑根本没有成功录入属性，所以才导致了调整值为 -5 和后面的问题

**Comment by MX-fox** [comment]
1.5.0 对于指令 `.r2#d优势` 行为与 1.4.5 不同

> 1.4.5行为
> <暮星>掷骰2次:
d优势=[{13 | 4 }]=13
d优势=[{5 | 5 }]=5

> 1.5.0行为
> 由于d优势，<暮星>掷骰2次:
d=17[d=17]=17
d=18[d=18]=18

**Comment by kenichiLyon** [comment]
> 1.5.0 对于指令 `.r2#d优势` 行为与 1.4.5 不同
> 
> > 1.4.5行为
> > <暮星>掷骰2次:
> > d优势=[{13 | 4 }]=13
> > d优势=[{5 | 5 }]=5
> 
> > 1.5.0行为
> > 由于d优势，<暮星>掷骰2次:
> > d=17[d=17]=17
> > d=18[d=18]=18

对于这里，我以用户角度出发提问DFL，150在执行2#d优势这样的命令的时候，对2#d优势的理想行为是如何的？与145保持一致？或是字母d后的字符作为参数识别？

**Comment by Xiangze-Li** [comment]
> ### 使用 .set dnd 时不会正确设置骰子面数
> 骰子提示已切换骰子面数，实际上没有，还是原来的骰子面数

准确地说，是默认面数被设置成了 0。

推测的原因：[dice/ext_dnd5e_template.go](https://github.com/sealdice/sealdice-core/blob/2296e2a984a130474830b77e8a007b0674d631f2/dice/ext_dnd5e_template.go#L12) 设置了 `DiceExpr: "d20"`，但这一字段并未在任何其他地方被使用。而之前在 CoC 模板中的做法，即设置 `DiceSides: 20`，并未进行。

**Comment by Xiangze-Li** [comment]
st show 和 st export 无法正确显示技能值

![image](https://github.com/sealdice/sealdice-core/assets/45380560/68e1a820-ba7f-4c74-a358-a68302fbf8e5)

**Comment by Szzrain** [comment]
> st show 和 st export 无法正确显示技能值
> 
> ![image](https://private-user-images.githubusercontent.com/45380560/344844715-68e1a820-ba7f-4c74-a358-a68302fbf8e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4ODg4ODMsIm5iZiI6MTcxOTg4ODU4MywicGF0aCI6Ii80NTM4MDU2MC8zNDQ4NDQ3MTUtNjhlMWE4MjAtYmE3Zi00Yzc0LWEzNTgtYTY4MzAyZmJmOGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDAyNDk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNjBkZjYxOTQzMzNkZjcxZTlmNDU1ODU5OWFlYjM0M2U5NmZjYmVlOWQ1NWVkOTVmMTdiN2MxZjMyZmMxYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.33lLQaxx016ajyX2POSTZtWiG3Xa-pWj9WIeQuE4gUg)

原因为 `.st export` 中直接调用了 `val.ToRepr()` 导致展示了原始值
