### ISSUE TITLE
[Bug]: 替换 DS 后掷默认骰详情输出不一致

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-core#863]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

![180efe3d9c0951e3684c1f9e5e18e77f](https://github.com/sealdice/sealdice-core/assets/45380560/361e6a08-9e01-4159-979d-9f7565959595)

### 如何复现

不明

### 你期望发生的

应与截图中 Kal'tsit 的格式类似，即 `d=[1d100=86]=86`，或 `d=[1d20=3]=3`

### 实际上发生的

/

### 日志文件

/

### 海豹核心版本

1.5.0-dev+20240702.82c386b

### 操作系统

/

### 帐号类型

/

**Comment by Xiangze-Li** [comment]
似与群组默认骰面有关

![1ea3f73c113a99ed98915610c0012b4f_720](https://github.com/sealdice/sealdice-core/assets/45380560/f41c5d8e-f080-45c2-9c46-1872a75c2c2f)

**Comment by Szzrain** [comment]
根本原因是因为没有设置群组面数用ds解析会失败，然后fall到v1
所以输出是rvm v1的格式
如果ds不支持这种写法，我的建议是趁早回滚

**Comment by fy0** [comment]
初步认为是因为ds使用表达式(string)替代了数值的骰子面数作为d的值，旧的配置需要转换后输入进去，但是可能没有配置正确

**Comment by fy0** [comment]
TODO: 表达式d应该显示计算过程，而不是采取与d100相同的显示
