### ISSUE TITLE
[Bug]: 并发写入了 ServiceAtNew ？

### ISSUE THREAD

**Issue by f44r** [sealdice/sealdice-core#865]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

fatal error: concurrent map iteration and map write

初步怀疑是自动保存时 ServiceAtNew 的锅。

### 如何复现

不明

### 你期望发生的

正常运行

### 实际上发生的

崩溃

### 日志文件

[报错日志.txt](https://github.com/user-attachments/files/16071459/default.txt)

### 海豹核心版本

1.4.5

### 操作系统

windows

### 帐号类型

应该与适配器无关

### 附加内容

#588 重构时可能需要注意

**Comment by PaienNate** [comment]
#937 已经解决。
