### ISSUE TITLE
[150 Bug]: DnD 属性豁免调整值计算错误

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-core#883]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

如题，从数值分析为 `x / 2 - 5` 的计算被多计算了一次，见下文示例数值

### 如何复现

1. 智力*=30 熟练=5，智力豁免加值为 5
2. 智力*=20 熟练=3，智力豁免加值为 0
3. 力量=10，力量豁免加值为 -5
4. 敏捷=16，敏捷豁免加值为 -4

### 你期望发生的

上述4种情况，加值应该依次为 15（10+5）、8（5+3）、0、3

### 实际上发生的

依次为 5、0、-5、-4

**分析**

5 = 10/2-5 + 5
0 = 5/2-5 + 3
-5 = 0/2-5
-4 = 3/2-5 

高度怀疑是计算调整值的 `x / 2 - 5` 公式被重复套用了

### 日志文件

x

### 海豹核心版本

1.5.0-dev+20240710.7495dcc

### 操作系统

x

### 帐号类型

x

### 使用协议

x

**Comment by fy0** [comment]
补一个，基础属性有熟练但是没有值被误认为只录入一条。
.st 智力*30:0 熟练:5
<User>的dnd5e属性录入完成，本次录入了1条数据
