### ISSUE TITLE
[150 Bug]: DnD 模式的 st show 格式无法区分加值来源

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-core#884]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

在 150 重写版中，DnD 模块的 st show 未能将技能的加值来源区分开，这是不能接受的

### 如何复现

录入属性和技能，再执行 st show

### 最低方案

维持 145 的格式，如一个 智力=20 熟练=3 且拥有宗教熟练的角色被表示成 `宗教:8[0]`，其中 `[0]` 表示直接的加值为 0，`8` 包括来自属性调整值的 5 和熟练加值 3。

### 希望的优化

将 8 表示成 5 + 3，以说明该技能拥有熟练

### 实际上发生的

`宗教*:8`，虽然能看出有熟练，但是无法区分额外加值、熟练加值和属性调整值

### 日志文件

x

### 海豹核心版本

1.5.0-dev+20240710.7495dcc

### 操作系统

x

### 帐号类型

x

**Comment by fy0** [comment]
啊？现在有加值的话是不是会显示呢？

**Comment by Xiangze-Li** [comment]
> 啊？现在有加值的话是不是会显示呢？

有额外加值的情况被表示为 `宗教*:9[1]`，但无加值情况的 0 不应被省略
