### ISSUE TITLE
[150] UI界面上进行自定义回复的v2兼容性标记

### ISSUE THREAD

**Issue by fy0** [sealdice/sealdice-core#892]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

等用户升级150后，无法知道哪些文本使用v2引擎

### 有什么好的想法？

启动时，预先以ctx.RunExpr跑一遍所有的自定义文本，对其兼容性进行标记（TextTemplateHelpItem.V2Compatible），并在UI界面上提示。

![image](https://github.com/sealdice/sealdice-core/assets/1579850/bc361d47-0342-4a02-b16d-ac09757c9232)

**Comment by Xiangze-Li** [comment]
方案有需要解答的问题：

1. 脚本并不能保证是无状态的，它可能通过变量赋值存储了上次运行的状态。在预运行的过程中可能破坏了上次运行的状态。
2. 在预运行过程中准备向脚本提供怎样的用户信息和群组信息？不合适的信息可能导致 a)脚本崩溃，b)无法覆盖脚本的所有分支，导致判断不准

**Comment by fy0** [comment]
> 方案有需要解答的问题：
> 
> 1. 脚本并不能保证是无状态的，它可能通过变量赋值存储了上次运行的状态。在预运行的过程中可能破坏了上次运行的状态。
> 2. 在预运行过程中准备向脚本提供怎样的用户信息和群组信息？不合适的信息可能导致 a)脚本崩溃，b)无法覆盖脚本的所有分支，导致判断不准

1. 模板变量并不允许常规方法修改，因此应该不用考虑动态修改
2. 我计划是不提供任何信息，遍历全部跑一遍，按照语法，format中动态赋值的那些都会toString()进去，空字符串不会造成任何影响。如果动态赋值的东西toString()就崩了，那么这种应归因为指令bug，与模板无关
