### ISSUE TITLE
[Feat](DnD): 被动察觉 (PP) 属性应当能够自动计算

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-core#893]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

被动察觉的数值永远是 `10 + 察觉(感知)总加值`, 应当实现为自动计算, 而不是依赖用户手动维护

**Comment by Szzrain** [comment]
其实 pp 也有白金币 Platinum pieces 的意思，我对此持保留意见

**Comment by fy0** [comment]
目前同义词表中已经将pp和被察紧密联系在一起了，所以先还是使用这个名字
![image](https://github.com/user-attachments/assets/6a796760-4b57-46e0-81c8-03d4f6884817)
