### ISSUE TITLE
[150 Bug](DnD): rc指令代骰读取数据错误

### ISSUE THREAD

**Issue by MX-fox** [sealdice/sealdice-core#900]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

rc指令代骰读取数据错误

### 如何复现

![cf226e0e4ad73f725a7dea27887e9be7_720](https://github.com/sealdice/sealdice-core/assets/106176511/e6cb4017-bc3e-498e-88bc-88f6de4596d9)

### 你期望发生的

正确读取代骰者数值

### 实际上发生的

读取发指令者的数值

### 日志文件

无

### 海豹核心版本

1.5.0-dev+20240711.064829a

### 操作系统

x

### 帐号类型

x

**Comment by Xiangze-Li** [comment]
代骰 rc 验证确有错误，代骰 st 指令也有问题

**Comment by MX-fox** [comment]
代骰 st 录卡正确，代骰 st show 显示的是发指令者的数值

**Comment by MX-fox** [comment]
![dd9d691e242e622e4f80b4dd09c0feb5](https://github.com/sealdice/sealdice-core/assets/106176511/babb505f-1a07-44b0-9819-6ef7e45977b4)
![0a28e57da754eafdee46336fd0e70fd0](https://github.com/sealdice/sealdice-core/assets/106176511/74a846e4-36b7-442a-92e1-ccbcffd52b8b)
自己st show就可以，代骰就不行
不清楚是哪一部分的问题，就先放在这里了
