### ISSUE TITLE
[150 Bug]: ri 先攻指令不支持表达式

### ISSUE THREAD

**Issue by MX-fox** [sealdice/sealdice-core#901]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

![image](https://github.com/sealdice/sealdice-core/assets/106176511/901d1b39-1495-4918-93f5-4eb3455c6a54)

### 如何复现

.ri =D20+3

### 你期望发生的

<master>对先攻点数设置如下:
 1. master: 3[1d15=3] + 2=5

### 实际上发生的

<master>的ri格式不正确!

### 日志文件

x

### 海豹核心版本

1.5.0-dev+20240711.064829a

### 操作系统

x

### 帐号类型

x

**Comment by Xiangze-Li** [comment]
fixed by #905
