### ISSUE TITLE
[150 Bug]: st <属性>±<表达式> 出错

### ISSUE THREAD

**Issue by MX-fox** [sealdice/sealdice-core#903]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

![6d11f065a6b1325a8b869a6dbf56cc1a](https://github.com/sealdice/sealdice-core/assets/106176511/9ef8f392-4654-4406-b1dd-c7740d3c8808)

### 如何复现

.st 自然+2

### 你期望发生的

正常加值

### 实际上发生的

返回0

### 日志文件

x

### 海豹核心版本

1.5.0-dev+20240711.064829a

### 操作系统

x

### 帐号类型

x

### 附加内容

不太了解dnd指令，不太清楚是否是指令错误，等待其他人复现

**Comment by Xiangze-Li** [comment]
fixed yb #905
