### ISSUE TITLE
[Bug](dnd): 正则表达式有误

### ISSUE THREAD

**Issue by FairyOwO** [sealdice/sealdice-core#907]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

ext_dnd5e.go中有两个正则表达式有误
master分支与main分支在不同行, 但都有这些问题
main分支的
755行 `re := regexp.MustCompile(`^优势|劣势|優勢|劣勢`)`
1447行 `re := regexp.MustCompile(`^优势|劣势`)`
master分支的
317行 `re := regexp.MustCompile(`^优势|劣势|優勢|劣勢`)`
839行 `re := regexp.MustCompile(`^优势|劣势`)`

### 如何复现

正则表达式匹配以其中一个为例
`^优势|劣势`
`11劣势` 匹配 `劣势`
`11优势` 没有匹配
`优势11` 匹配 `优势`
`劣势11` 匹配 `劣势`
`优势|劣势` 匹配 `优势` `劣势` 
`劣势|优势` 匹配 `劣势`

### 你期望发生的

只匹配 由优势或者劣势开头

### 实际上发生的

不由劣势开头也会被匹配到
![image](https://github.com/user-attachments/assets/53f714f5-391f-4495-950a-72767b0af868)

### 日志文件

*

### 截图

*

### 海豹核心版本

1.5

### 操作系统

*

### 帐号类型

*

**Comment by Xiangze-Li** [comment]
fixed by #905
