### ISSUE TITLE
JS 插件能够获取当前插件列表

### ISSUE THREAD

**Issue by FlameTEXT** [sealdice/sealdice-core#91]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

一个JS插件依赖另一个插件时，需要判断依赖存不存在。

**Comment by Szzrain** [comment]
仅仅是判断依赖的话可以用ext.find

**Comment by fy0** [comment]
通过ext.find应该能够获取
