### ISSUE TITLE
[Bug]: 同用数据库的海豹在一个群时，该群log会不定时消失

### ISSUE THREAD

**Issue by dunasi** [sealdice/sealdice-core#911]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

同用数据库的海豹大小号在一个群里时，已将其中一个海豹bot关闭，记录log时一切正常，但搁几天后会不定时的log消失，仅剩下日志名称
![QQ图片20240714234933](https://github.com/user-attachments/assets/45f3fe18-3590-4e86-bd09-d57b0715b335)
![QQ图片20240714234146](https://github.com/user-attachments/assets/eedaef18-8ea5-4ef9-8737-b26df9a21bad)

### 如何复现

已尝试复现，但失败了，因为记录log时是正常的，无法判断为什么时候会丢失
![QQ图片20240714234938](https://github.com/user-attachments/assets/d575af9f-0c12-4574-b0f2-cc76bed10edd)

### 你期望发生的

log不会丢失

### 实际上发生的

无法确认什么时候丢失，未end的log无法找回

### 日志文件

[record.log](https://github.com/user-attachments/files/16227979/record.log)
[record-2024-07-14T11-29-53.925.log](https://github.com/user-attachments/files/16227980/record-2024-07-14T11-29-53.925.log)

### 海豹核心版本

1.4.5+20240410

### 操作系统

Linux

### 帐号类型

qq

**Comment by MX-fox** [comment]
数据丢失原因为 wal 未落盘，重启后丢失。未落盘原因未知，但与大小号无关。

**Comment by Xiangze-Li** [comment]
WAL未能正确落盘据称被视为可以接受的数据损失
