### ISSUE TITLE
以st格式导出角色卡

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-core#93]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在跨骰子使用同一角色时，往往需要在第一个骰子`st show`，手动将人物属性和状态更新回excel人物卡，再导入第二个骰子。这过程耗时且容易遗漏数值。

### 有什么好的想法？

希望能够提供`st`和`pc`的子指令，将当前角色卡或某个保存的角色卡输出为录入格式，其中也要包含自定义技能和标准技能的初始值。这样的话，用户就可以直接复制骰子发出的内容，输入给另外的骰子。

考虑到多个骰子互相干扰的可能，或许可以略去`.st`指令或`.`前缀，抑或是增加一个干扰的前缀如`(`

**Comment by fy0** [comment]
和dnd那个一样，准备加入 .st export

**Comment by fy0** [comment]
已实现 caafee7
