### ISSUE TITLE
[150 Bug]:  CoC 和 DnD 规则对 int 和 str 进行检定时报错

### ISSUE THREAD

**Issue by MX-fox** [sealdice/sealdice-core#944]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

![image](https://github.com/user-attachments/assets/a6b60aa3-f20d-45a5-9962-67279dc4d5f1)

### 如何复现

.ra str
.ra int

### 你期望发生的

进行智力/力量鉴定

### 实际上发生的

你输入的表达式并非文本类型

### 日志文件

x

### 截图

x

### 海豹核心版本

1.5.0-dev+20240724.b794f53

### 操作系统

x

### 帐号类型

x

### 附加内容

其他属性鉴定未复现，就这来个属性英文有问题

**Comment by Xiangze-Li** [comment]
![image](https://github.com/user-attachments/assets/94b57094-c55f-46b2-9887-a3e1e5794694)

**Comment by fy0** [comment]
我敲，非常坏！

**Comment by kenichiLyon** [comment]
初步考虑为ds设置的变量类型名与CoC的智力和力量英文缩写冲突。个人建议改ds或150暂时不实现英文指令，在实现i18n后将英文缩写指令归入其中。

**Comment by kenichiLyon** [comment]
> 初步考虑为ds设置的变量类型名与CoC的智力和力量英文缩写冲突。个人建议改ds或150暂时不实现英文指令，在实现i18n后将英文缩写指令归入其中。

考虑到i18n只是治标不治本，建议仍然是尽快更改ds相关适配
