### ISSUE TITLE
是否考虑继续对接OpenShamrock？

### ISSUE THREAD

**Issue by kenichiLyon** [sealdice/sealdice-core#947]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

[OpenShamrock](https://github.com/whitechi73/OpenShamrock/releases/tag/1.1.1) 近期仓库恢复 public ，同时发版 1.1.1 。里面包含 OneBot 分支的发布。同时考虑到 OpenShamrock 有新功能的发布，海豹是否还会考虑对接 OpenShamrock？

**Comment by Xiangze-Li** [comment]
如果 OpenShamrock 仍然提供 OB11 协议接口，就不存在「对接」问题，只存在是否要在教程中介绍和介绍到什么程度的问题
