### ISSUE TITLE
希望插件配置项获取时可以先判断key是否存在

### ISSUE THREAD

**Issue by a001009** [sealdice/sealdice-core#952]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

使用getxxxconfig函数获取插件配置项时，如果key不存在会报一个空指针的错误

### 有什么好的想法？

希望能在获取配置项的时候，先判断一下key是否存在

**Comment by MX-fox** [comment]
![屏幕截图 2024-07-29 023919](https://github.com/user-attachments/assets/e3308dcc-1490-4de6-8666-dbcc4ef487cb)
qing
请将注册插件配置项写在前面

**Comment by JustAnotherID** [comment]
不会提供，插件自己注册自己的 config，是否有对应 key 是插件自己的代码逻辑问题。

**Comment by JustAnotherID** [comment]
不会提供，插件自己注册自己的 config，是否有对应 key 是插件自己的代码逻辑问题。
