### ISSUE TITLE
关于插件配置项

### ISSUE THREAD

**Issue by a001009** [sealdice/sealdice-core#954]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

鉴于之前的issue被秒关，但是还有疑问，所以再发一个，这个配置项，既然在注册之后，会保留下来，但是下次代码调用有需要重新注册，那么意义在哪里，再次注册值会覆盖，直接声明一个变量还用的着打那么一大串内置api代码？反正一样在代码生命周期结束就都作废了，对开发者不如直接改代码，对其他使用者也不方便，既然做了，做个半成品干什么呢，还告诉我判断有没有注册是插件代码逻辑该负责的事，那某id我问你，为什么数据库和牌堆在不存在的时候都有对应的处理机制，自己不行就说不行，没那个思路就别干开发了

**Comment by Szzrain** [comment]
1. 注意你的提问态度，这是个开源项目，你不是甲方，维护者也不是你爹，没义务为你解决问题
2. 插件配置项重复注册并不会覆盖已设置的值，这样设计的目的是区分正在使用的配置项和未在使用的配置项

**Comment by kenichiLyon** [comment]
未贡献代码所以不回复代码层面问题，仅从issue方面回复。
1、请按规范提交issue，前一个issue不规范提交，仅提出需求而未将遇到问题具体日志和代码附上。前一个issue也并没有被秒关，两位member已经回复，回复后关闭issue。不符合您所提出的秒关issue
2、问题表述不清，您需求是何，需要通过插件配置项判定key是否存在实现哪个场景的什么问题？我们只能通过字面意思回复。
3、因为core仓库maintainer只有几位，实现有缺陷是必然的，海豹也支持所有人提交pr以修复缺陷。另外，精神甲方不可取，海豹是开源项目而非闭源项目，贡献者也并不是你的父母必须要给你解决问题。请您下次注意提issue的态度。情绪不能解决问题，就事论事，给足信息才能。

**Comment by MX-fox** [comment]
![bf703fe25bbf56859d8ea7a0ce64f23e](https://github.com/user-attachments/assets/0fd3c7ce-3232-4d13-8409-81c8cb651c2a)

**Comment by JustAnotherID** [comment]
> 那某id我问你，为什么数据库和牌堆在不存在的时候都有对应的处理机制，自己不行就说不行，没那个思路就别干开发了

用不来别用，自己不会用就来说不行，没那个思路就别干开发了。
