### ISSUE TITLE
[Bug]: DND属性检定表达式写法有误

### ISSUE THREAD

**Issue by GUERdugujian** [sealdice/sealdice-core#968]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

如图，应该输出属性调整值的位置变成了原值。
技能检定的表达式正常。

### 如何复现

。ra敏捷（或任意属性）

### 你期望发生的

2[D20] + 5[敏捷调整值5]+2 = 9，
或者能够在[]内标明原值，比如：2[D20] + 5[敏捷属性值20=>调整值+5]+2 = 9

### 实际上发生的

如图

### 日志文件

如图

### 截图

![7821193667d0837b5fab85410562adf1](https://github.com/user-attachments/assets/6a677919-612b-44ed-b595-0d83be0ad104)
![7fd02c4b4d6979a077485569e89ac6ba](https://github.com/user-attachments/assets/eddaa153-353d-4c95-8bae-8b8839a3f1c1)

### 海豹核心版本

150dev7.31

### 操作系统

Windows server 2022

### 帐号类型

QQ

**Comment by fy0** [comment]
已修复于 #964，左侧不应该是20而是5

**Comment by GUERdugujian** [comment]
> 已修复于 #964，左侧不应该是20而是5

个人认为可以像提议那样，在[]内保留对应原值，以方便检查数据是否出错

**Comment by kenichiLyon** [comment]
已follow up在 #969 ，以便区分，建议关闭此issue切换到 #969 评论区再行讨论。
