### ISSUE TITLE
在Win7/2008系统下弹出不兼容警告

### ISSUE THREAD

**Issue by fy0** [sealdice/sealdice-core#970]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

Win7 / 2008 下拉格兰 ncqq等工具已经无法正常运行

### 有什么好的想法？

启动海豹时，在Win7/2008系统下弹出不兼容警告。

与此同时，已知：
- WinServer 2012 下，拉格兰和ncqq可运行，只是出现控制台乱码

还需要了解：
- MacOS 10.13 和 10.14 的情况，希望使用者现身说法

如果未来2012和macos的两个版本都不必再支持，那么会择机将golang从1.20版本向上升级

**Comment by Xiangze-Li** [comment]
我保留我的意见：直接放弃支持。

由于意见冲突，我将不参与此issue相关的任何事务

**Comment by kenichiLyon** [comment]
我意见同 @Xiangze-Li ，相关issue的手册工作我也不会参与。
