### ISSUE TITLE
自动退群需要一个白名单机制

### ISSUE THREAD

**Issue by f44r** [sealdice/sealdice-core#971]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

有些群聊虽然不发言但不应该退出（例如放置备用骰的用户群）

同样是用户群的情景，有时可能出现用户群意外放进黑名单用户导致骰子退群，虽然无关紧要但确实麻烦。

需要扩展白名单机制，避免骰子自动退出白名单群。

**Comment by kenichiLyon** [comment]
#791 应为前提。先fix #791 再行fix自动退群功能似乎更好？

**Comment by f44r** [comment]
没细看提交内容，所说功能已经被实现过了，该在手册里加退群机制的说明了。
