### ISSUE TITLE
希望150dev日志部分的{$t当前记录条数}变量在logend时暂时保留

### ISSUE THREAD

**Issue by bugtower100** [sealdice/sealdice-core#974]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在更新150dev版本后，海豹内置变量{$t当前记录条数}在logend时会被丢弃而无法调用，因此在logend文案处无法显示日志记录总条数
150（现状）：
![612f4dcbf1295be740b5abf08e1d12d2](https://github.com/user-attachments/assets/8302151b-54c0-4ba9-b760-faac79a22b6f)
自定义文案：
![fb3b8269b251792a1aa220d14ef1226c](https://github.com/user-attachments/assets/277fb361-c91a-4c87-8c9b-0655bfca60e2)

### 有什么好的想法？

希望该变量能够像145一样保留并可被调用，如图（145版本）状况：
![c7c838abcf8408796d42860031200121](https://github.com/user-attachments/assets/92ebdd9c-9285-4852-88f9-b63aa2e440fc)

**Comment by MX-fox** [comment]
补充：150与145不一致的原因在于
ds 会将由海豹赋予的 `$t临时变量` 在本次会话结束后回收，而 logend 并未对此变量赋值，故而为 0。
而 145 中 logend 的 `$t当前记录条数` 实际为 logon/logoff 时赋值，并非真实的 `$t当前记录条数`。

**Comment by fy0** [comment]
想到一个办法，尝试一下，在log end文本中进行一个：
$t当前记录条数 = $t当前记录条数

这样的操作

**Comment by bugtower100** [comment]
> 想到一个办法，尝试一下，在log end文本中进行一个： $t当前记录条数 = $t当前记录条数
> 
> 这样的操作

>尝试了一下不太行，还是0条。介于手机不好贴图，我发一下补充部分:
>
>{%
if $g暂停时间==0
{ $g暂停时间=$tTimestamp;
$g跑团时间=$g跑团时间+$g暂停时间-$g继续时间 };
$t时=$g跑团时间/3600;
$t分=($g跑团时间%3600)/60;
$t秒=$g跑团时间%60;
$t当前记录条数 = $t当前记录条数;
`让我看看，你们花费了{$t时}时{$t分}分{$t秒}秒去演绎『{$t记录名称}』这段故事，而命运之书上则书写了 {$t当前记录条数}条...哼哼，收获颇丰~\f
我收获了不错的故事，而你们在这次的表演（旅途）中又获得了什么呢？可以的话也讲给我听听吧~
[记录已经关闭]`
%}

**Comment by bugtower100** [comment]
> 想到一个办法，尝试一下，在log end文本中进行一个： $t当前记录条数 = $t当前记录条数
> 
> 这样的操作

我尝试了一下，但是还是显示0条，改动后如下:
>{%
if $g暂停时间==0
{ $g暂停时间=$tTimestamp;
$g跑团时间=$g跑团时间+$g暂停时间-$g继续时间 };
$t时=$g跑团时间/3600;
$t分=($g跑团时间%3600)/60;
$t秒=$g跑团时间%60;
$t当前记录条数 = $t当前记录条数;
`让我看看，你们花费了{$t时}时{$t分}分{$t秒}秒去演绎『{$t记录名称}』这段故事，而命运之书上则书写了 {$t当前记录条数}条...哼哼，收获颇丰~\f
我收获了不错的故事，而你们在这次的表演（旅途）中又获得了什么呢？可以的话也讲给我听听吧~
[记录已经关闭]`
%}

**Comment by fy0** [comment]
> $t当前记录条数 = $t当前记录条数

构建了一个场景试了下：

我这里使用的是log on：

![image](https://github.com/user-attachments/assets/7d937813-9d3c-4746-b252-80df659ac4de)

无法继续，没能找到记录: {$t记录名称} {$t记录名称=$t记录名称; ''}

这样是可以被记录的。
![image](https://github.com/user-attachments/assets/1c119068-a98a-48a2-a943-e7928a2cd902)


=========

然后在log off里使用同样的方法成功了。

{$t当前记录条数 = $t当前记录条数; ''}

![image](https://github.com/user-attachments/assets/255a8f15-f6c0-4c76-94d4-6853d0a98fab)


其实还是因为这里 “$t当前记录条数” 和用户自己赋值的 $t 变量不太一样，未来择机拿掉$t以作为区分

**Comment by Director259** [comment]
> > $t当前记录条数 = $t当前记录条数
> 
> 构建了一个场景试了下：
> 
> 我这里使用的是log on：
> 
> ![image](https://private-user-images.githubusercontent.com/1579850/356190602-7d937813-9d3c-4746-b252-80df659ac4de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTUxNTUsIm5iZiI6MTcyMzExNDg1NSwicGF0aCI6Ii8xNTc5ODUwLzM1NjE5MDYwMi03ZDkzNzgxMy05ZDNjLTQ3NDYtYjI1Mi04MGRmNjU5YWM0ZGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMTEwMDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmFhNjUzODE1MjE2MmQzZWM2Y2VjYmIzNzA2ZTI5ZDA1NmQyMzFiY2RkNGE5MDMwMmIzYWQzOWUyMjM2ZjQyYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jka5r9hM9azi0v8uezVtg7zsMV1u9QAT9C2yHG4Wxyo)
> 
> 无法继续，没能找到记录: {$t记录名称} {$t记录名称=$t记录名称; ''}
> 
> 这样是可以被记录的。 ![image](https://private-user-images.githubusercontent.com/1579850/356190534-1c119068-a98a-48a2-a943-e7928a2cd902.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTUxNTUsIm5iZiI6MTcyMzExNDg1NSwicGF0aCI6Ii8xNTc5ODUwLzM1NjE5MDUzNC0xYzExOTA2OC1hOThhLTQ4YTItYTk0My1lNzkyOGEyY2Q5MDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMTEwMDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDkwZjE5MzI4MjFjZTg5YmFlMTE1YmUwNjU3MGFhN2U5MzcxN2VmYzUwZjYwMDhhOGQ5YWFkNTNkNjBlOGVlOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AFhhV3Va4NW-RM_LMUUDGBokBc6RsK1kRtfZ-vdeqQI)
> 
> =========
> 
> 然后在log off里使用同样的方法成功了。
> 
> {$t当前记录条数 = $t当前记录条数; ''}
> 
> ![image](https://private-user-images.githubusercontent.com/1579850/356191720-255a8f15-f6c0-4c76-94d4-6853d0a98fab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTUxNTUsIm5iZiI6MTcyMzExNDg1NSwicGF0aCI6Ii8xNTc5ODUwLzM1NjE5MTcyMC0yNTVhOGYxNS1mNmMwLTRjNzYtOTRkNC02ODUzZDBhOThmYWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMTEwMDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDJjYmRhNmE3Y2JhMTRjZGU0MWRiYjFlMjc5NmFhODhkYjc5MzUzNjc0NTk0NmFmNzlmNzNhNzJkZjk5YjFkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._xBEBtTn3oefElfszxf_R7ubA-vgQkFaDvTxk4BvHBk)
> 
> 其实还是因为这里 “$t当前记录条数” 和用户自己赋值的 $t 变量不太一样，未来择机拿掉$t以作为区分

我看了下bug需要的应该是{$t当前记录条数}在lodend时能有类似于我上次#601条提出的{$t记录名称}的效果？而且这个变量海豹本身有提供，自行赋值使用是不是有些绕弯子了

**Comment by bugtower100** [comment]
> {$t当前记录条数 = $t当前记录条数; ''}

我尝试了一下在lognew/on/off/end处添加了“$t当前记录条数 = $t当前记录条数;”，这样写的确可以在end时抓到条数了，不过我和上面木木的想法一样，这种自行赋值使用有点绕弯子（思）
