### ISSUE TITLE
jsvm应对while等无限循环或死递归进行一些限制

### ISSUE THREAD

**Issue by lxy071130** [sealdice/sealdice-core#98]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

现在海豹没有对jsvm所能执行的次数进行任何的限制，这会导致非常容易写出（有意或无意）的有害插件，如：
```javascript
while (true){
    a += 1;
    arr.push(a)
}
```
这种代码，会在一瞬间消耗所有资源导致卡死。且，在触发这种插件时，海豹不会退出，而是一种类似于死机的状态，这是极其不利的。应该至少做到在重载插件时进行一次检查，防止这种情况。

### 有什么好的想法？

暂无，等待补充

**Comment by Szzrain** [comment]
插件作者的愚蠢行为不应该由jsvm进行约束，如此的话没有边界条件的递归等等难道也要管么
