### ISSUE TITLE
给指令测试的UI:1001加个头像

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-core#99]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

指令测试里面，海豹有头像，但是发指令的这边没有头像。有可能的话请也给这边加个头像吧

![image](https://user-images.githubusercontent.com/45380560/233813451-5546618e-b532-487f-ab88-f05e9afb2a94.png)

**Comment by Szzrain** [comment]
这个猫猫叹号就是头像
