### ISSUE TITLE
[Bug]: 关于自定义回复功能的【删除条件】按钮：只会删除最末行条件

### ISSUE THREAD

**Issue by lcmdyc** [sealdice/sealdice-core#990]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

如题，某回复存在多个触发条件时，无论点击哪一条的**删除条件**按钮，都只会从最底下一条开始删除

### 如何复现

如下方截图所示。
截图仅演示点击**首行**删除条件的结果，实际**无论点击哪一条**删除条件都会造成“这是测试2”条件行被删除的结果。

### 你期望发生的

同时存在条件ABC等，点选**A行**的删除条件按钮，则**删除对应A行条件**。

### 实际上发生的

同时存在条件ABC等，点选**任意**删除条件按钮，则**删除最末行条件**。

### 日志文件

无日志文件

### 截图

![QQ20240812-035935](https://github.com/user-attachments/assets/125f462b-9c3a-42f9-b5db-6419be8240a1)
![QQ20240812-035736](https://github.com/user-attachments/assets/98c0f9f5-34d1-4071-9086-c11d61a00127)

### 海豹核心版本

1.4.6+20240810

### 操作系统

Windows 10

### 帐号类型

单个QQ账号内置客户端

**Comment by Xiangze-Li** [comment]
1.4.6-beta+20240807.22fd4f2 未复现
